### ISSUE TITLE
sharelatex-web stops working after db read error

### ISSUE THREAD

**Issue by engeliii23** [sharelatex/sharelatex#164]
Hi guys

Thanks for the awesome sharelatex package(s) and support. I sucessfully installed everything and it worked for some weeks but after creating, updating and deleting some projects and users (finally i deleted all of them), i receive this (for me) strange exception in the log file:

```
Exception: TypeError: Cannot read property 'readOnly_refs' of undefined
  at Object.module.exports.ProjectGetter.populateProjectWithUsers (/var/www/sharelatex/web/app/js/Features/Project/ProjectGetter.js:80:30)
  at /var/www/sharelatex/web/app/js/Features/Editor/EditorController.js:81:30
  at /var/www/sharelatex/web/app/js/Features/Project/ProjectGetter.js:29:16
  at /var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:158:16
  at commandHandler (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:651:16)
  at /var/www/sharelatex/web/node_modules/metrics-sharelatex/mongodb.coffee:39:15
  at /var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1670:9
  at Server.Base._callHandler (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
  at /var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
  at [object Object].MongoReply.parseBody (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
  at [object Object].EventEmitter.emit (events.js:95:17)
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
  at [object Object].EventEmitter.emit (events.js:98:17)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```
May somebody help me with that / is this my wrong or something in the code?

OS: Ubuntu 14.04.1 x86_64
MongoDB: 2.4.9

Thanks for your support!

Cheers, engeliii23

**Comment by sisonath** [comment]
Hello
