### ISSUE TITLE
copy project does not provide feedback on completion

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/sharelatex#183]
When copying a project, the dialogue shows "copying..."
However it does not dismiss or provide feeback when the copying is complete.
The copying works well but it's confusing to know when the copy is complete.
copying of files also seems to take a very long time (more than uploading them!).
It seems that copying may be slower for files in sub-directories, not sure what is holding it up.

log
```
2014-09-14T04:50:24.589Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/Makefile, sl_req_id=null, rev=0)
[2014-09-14T04:50:24.590Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store queued up for processing (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/immigration.plt, sl_req_id=null, rev=0)
[2014-09-14T04:50:24.591Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/pie_r.gnu, sl_req_id=null, rev=0)
[2014-09-14T04:50:24.591Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store queued up for processing (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/Makefile, sl_req_id=null, rev=0)
[2014-09-14T04:50:24.591Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/pie.dat, sl_req_id=null, rev=0)
[2014-09-14T04:50:24.592Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store queued up for processing (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/pie_r.gnu, sl_req_id=null, rev=0)
[2014-09-14T04:50:24.592Z]  INFO: web-sharelatex/1447 on sharelatex.server: sending file to third party data store queued up for processing (project_id=54151da0cfaccca7058854cb, user_id=53db105f0aa775bf095287d8, path=/graphs/pie.dat, sl_req_id=null, rev=0)
```

actually, also found an error in log files
```
[2014-09-14T04:58:24.777Z] ERROR: web-sharelatex/1447 on sharelatex.server: error coping file in s3 (project_id=54151da0cfaccca7058854cb, folder_id=54151f08cfaccca7058854e1, originalProject_id=54151bf4cfaccca7058854a2)
    Error: socket hang up
      at createHangUpError (http.js:1472:15)
      at Socket.socketOnEnd [as onend] (http.js:1568:23)
      at Socket.g (events.js:180:16)
      at Socket.emit (events.js:117:20)
      at _stream_readable.js:929:16
      at process._tickCallback (node.js:419:13)

    --
    origonalFileRef: {
      "_id": "54151c83cfaccca7058854c1",
      "rev": 0,
      "created": "2014-09-14T04:41:39.132Z",
      "name": "prod_bs4.jpg"
    }
```

**Comment by henryoswald** [comment]
I believe we fixed this problem a few months ago so closing.
