### ISSUE TITLE
Unable to access Sharelatex from other than localhost

### ISSUE THREAD

**Issue by qmaxquique** [sharelatex/sharelatex#193]
**Hello,**
I'm trying to make work Sharelatex behind a **nginx 1.5.2 proxy, node v0.10.29.** (running on ubuntu 10.04 in an OpenVz container)
(I'm sorry, but I'm not a node/Js developer... just a sysadmin trying to install this app)

-It's like Sharelatex, by default, is only working for connections coming from localhost as the port is not responding to outside ingoing connections, and nginx drops a 502. (I can get the app with lynx and telnet at port 3000 from console)

I tried:
- Set behindProxy as true => same results.
- Set the apis: web: url to the final proxied url => same result

- Then I also tried uncommenting this (with the idea to change localhost by 0.0.0.0)
```
        internal:
               web:
                       port: webPort = 3000
                       host: "localhost"
```

but I get error output this anyway:
```
root@qmaxquique344:/sharelatex# grunt run
Running "concurrent:all" (concurrent) task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task

Running "execute:web" (execute) task
-> executing /sharelatex/web/app.js

Running "execute:track-changes" (execute) task
-> executing /sharelatex/track-changes/app.js

Running "execute:docstore" (execute) task
-> executing /sharelatex/docstore/app.js

/sharelatex/config/settings.development.coffee:64
    ]({
     ^
TypeError: object is not a function
    at Object.<anonymous> (/sharelatex/config/settings.development.coffee:64:6)
    at Object.<anonymous> (/sharelatex/config/settings.development.coffee:89:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (/sharelatex/track-changes/node_modules/settings-sharelatex/node_modules/coffee
-script/lib/coffee-script/coffee-script.js:24:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/sharelatex/track-changes/node_modules/settings-sharelatex/Settings.coffee:
42:30)
    at Object.<anonymous> (/sharelatex/track-changes/node_modules/settings-sharelatex/Settings.coffee:
54:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (/sharelatex/track-changes/node_modules/settings-sharelatex/node_modules/coffee
-script/lib/coffee-script/coffee-script.js:24:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/sharelatex/track-changes/node_modules/settings-sharelatex/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/sharelatex/track-changes/app.js:4:14)
    at Object.<anonymous> (/sharelatex/track-changes/app.js:61:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Warning: -> error 8 /sharelatex/track-changes/app.js (740ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.

        Aborted due to warnings.
```

**Any kind of help is much appreciated!**

**Comment by T7o7heVV** [comment]
@valx76 thanks for the editing idea! =)

For anyone who wants it more public than just one IP, you can also allow any:

* host = -1; *
( file = web/app.js )
