### ISSUE TITLE
ShareLaTex in a virtual machine (VMware Workstation)

### ISSUE THREAD

**Issue by 2L40K** [sharelatex/sharelatex#235]
I'm trying to install ShareLaTex in a virtual machine. Two configurations tested:

1. VMware Workstation 10, `ubuntu-14.04.1-server-amd64.iso`, full manual install from the wiki.
2. VMware Workstation 11, `ubuntu-12.04.5-server-amd64.iso`, semi-auto install using `sharelatex_0.1.0_amd64.deb` from the wiki.

In both cases:

1. ShareLaTex appears to work just fine, although I did only simple tests.
2. But the virtual machine boots slowly, it takes about 20-30 seconds to accept login and password on the terminal.
3. After clean install on first boot there are errors in the logs, and they are almost the same in both cases. 
4. More errors appear in the logs when ShareLaTex is used.

Dependences I have (second configuration, will see the first):
```
nodejs = 0.10.33
redis-server = 2.8.18
mongodb-org = 2.6.5
```

I think, It's either these dependences are too new, or there is/are some bug(s).

For example first boot after clean install, second configuration, only error lines:
(Will post full logs if needed.)

**web.log**
```
Exception: Error: failed to connect to [127.0.0.1:27017]                                            
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongod$
  at [object Object].emit (events.js:106:17)                                                        
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongod$
  at [object Object].emit (events.js:98:17)                                                         
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mon$
  at Socket.emit (events.js:95:17)                                                                  
  at net.js:440:14                                                                                  
  at process._tickCallback (node.js:419:13)
```

**chat.log**
```
events.js:72                                                                                        
        throw er; // Unhandled 'error' event                                                        
              ^                                                                                     
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED                             
    at RedisClient.on_error (/var/www/sharelatex/chat/node_modules/redis/index.js:185:24)           
    at Socket.<anonymous> (/var/www/sharelatex/chat/node_modules/redis/index.js:95:14)              
    at Socket.emit (events.js:95:17)                                                                
    at net.js:440:14                                                                                
    at process._tickCallback (node.js:419:13)
```

**document-updater.log**
```
/var/www/sharelatex/document-updater/app/js/DispatchManager.js:63                                   
                throw error;                                                                        
                      ^
```

**track-changes.log**
```
events.js:72                                                                                        
        throw er; // Unhandled 'error' event                                                        
              ^                                                                                     
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED                             
    at RedisClient.on_error (/var/www/sharelatex/track-changes/node_modules/redis/index.js:185:24)  
    at Socket.<anonymous> (/var/www/sharelatex/track-changes/node_modules/redis/index.js:95:14)     
    at Socket.emit (events.js:95:17)                                                                
    at net.js:440:14                                                                                
    at process._tickCallback (node.js:419:13)
```

**Comment by 2L40K** [comment]
Most probably - Yes, everything works. But I am not absolutely sure about data loss on shutdown.

There other issues I discovered since the last time.
* `Gnuplot` doesn't work. Neither the original, nor the latest version from `ppa:gladky-anton/gnuplot`. Error message says, that LaTeX can't find the corresponding file, that `Gnuplot` must have produced.
* `Asymptote` doesn't work. No error message, but there was no graphics produced.
* Spell-check for languages other than English doesn't work. Installed all `aspell` dictionaries. Enabled some of them via the configuration file. Corresponding options appeared in the drop down menu, but only the English one worked.

For `Gnuplot` and `Asymptote` used these [examples](https://github.com/sharelatex/clsi-sharelatex/tree/master/test/acceptance/fixtures/examples) too, but the result was the same.

**Comment by henryoswald** [comment]
we have a docker image now available which can be used for this sort of problem in the future https://github.com/sharelatex/sharelatex-docker-image
