### ISSUE TITLE
track-changes error and history not working anymore

### ISSUE THREAD

**Issue by migueln** [sharelatex/sharelatex#248]
Hi, 

After changing the minifyjs option from false to true, generating the js files and upgrading my sharelatex installation, I have some issues with the changelog of all my documents.

This is what I see in the logs after a restart of sharelatex.

```
[2015-01-13T18:14:56.771Z] ERROR: track-changes/57 on sharelatex: inconsistent doc versions (doc_id=54ad0d4784879f4a008abcc0, project_id=53c2c00c5a1b881331a57b42)
    Error: Tried to apply raw op at version 4224 to last compressed update with version 619
        at /sharelatex/track-changes/app/js/UpdatesManager.js:41:21
        at /sharelatex/track-changes/app/js/MongoManager.js:45:20
        at /sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/collection.js:203:9
        at /sharelatex/track-changes/node_modules/metrics-sharelatex/mongodb.coffee:42:29
        at Server.Base._callHandler (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
        at /sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
        at MongoReply.parseBody (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
        at null.<anonymous> (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
        at emit (events.js:95:17)
        at null.<anonymous> (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
        at emit (events.js:98:17)
        at Socket.<anonymous> (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)
[2015-01-13T18:14:56.787Z]  INFO: track-changes/57 on sharelatex: mongo request (query_type=insert, collection=sharelatex.docHistory, response-time=14)
[2015-01-13T18:14:56.790Z] ERROR: track-changes/57 on sharelatex: an internal error occured
    Error: Tried to apply raw op at version 4224 to last compressed update with version 619
        at /sharelatex/track-changes/app/js/UpdatesManager.js:41:21
        at /sharelatex/track-changes/app/js/MongoManager.js:45:20
        at /sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/collection.js:203:9
        at /sharelatex/track-changes/node_modules/metrics-sharelatex/mongodb.coffee:42:29
        at Server.Base._callHandler (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
        at /sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
        at MongoReply.parseBody (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
        at null.<anonymous> (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
        at emit (events.js:95:17)
        at null.<anonymous> (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
        at emit (events.js:98:17)
        at Socket.<anonymous> (/sharelatex/track-changes/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)
```

**Comment by migueln** [comment]
Hi again,

I'm doing some tests with the history.

If I make a new document and commit some changes, I can see the snapshots in the history, but they do not work very well and give me some crashes:

```
[2015-01-13T19:23:50.613Z] ERROR: track-changes/80 on sharelatex: an internal error occured
    ConsistencyError: Inserted content, '
    testme
    ', does not match text to be removed, 'uction}
    '
        at new ConsistencyError (/sharelatex/track-changes/app/js/DiffGenerator.js:6:13)
        at Object.module.exports.DiffGenerator.rewindOp (/sharelatex/track-changes/app/js/DiffGenerator.js:30:17)
        at Object.module.exports.DiffGenerator.rewindUpdate (/sharelatex/track-changes/app/js/DiffGenerator.js:21:33)
        at Object.module.exports.DiffGenerator.rewindUpdates (/sharelatex/track-changes/app/js/DiffGenerator.js:42:33)
        at /sharelatex/track-changes/app/js/DiffManager.js:83:43
        at /sharelatex/track-changes/app/js/DiffManager.js:28:18
        at Request._callback (/sharelatex/track-changes/app/js/DocumentUpdaterManager.js:32:18)
        at Request.self.callback (/sharelatex/track-changes/node_modules/request/request.js:122:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/sharelatex/track-changes/node_modules/request/request.js:888:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/sharelatex/track-changes/node_modules/request/request.js:839:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickCallback (node.js:442:13)
```

**Comment by henryoswald** [comment]
It looks like they have gotten out of sync some how. Im not sure how that could have happened. Are your clients connecting to the server without issue?

**Comment by migueln** [comment]
Well, my users still sue that sharelatex, but without the history. 

I had some issues however with one of my documents. Some of the latest changes were lost after a server crash / restart (the system is installed in a docker container). Looking into the database I see some of these changes there, but for me it's a real pain to try to dump the database content manually. 

Is there any documentation on how sharelatex stores its data in the database?.

**Comment by henryoswald** [comment]
We don't have any good documents I am afraid. I would guess this happened if your redis is running without any persistence. I would enable AOF http://redis.io/topics/persistence

**Comment by migueln** [comment]
Ok, I will try to download a working copy of all our documents and remake the sharelatex image. Or try to recover the database (if that is the problem).

**Comment by henryoswald** [comment]
If redis crashed and lost its data it is possible the history in some of
the docs will always be broken I am afraid.

On Thu, Jan 15, 2015 at 2:32 PM, Miguel N. <notifications@github.com> wrote:

> Ok, I will try to download a working copy of all our documents and remake
> the sharelatex image. Or try to recover the database (if that is the
> problem).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/248#issuecomment-70093040>
> .
>



-- 
Henry Oswald
shareLaTeX.com creator

**Comment by migueln** [comment]
Hi again,

Would it be easy to wipe the entire history of our projects keeping only the current data or should we start from scratch?.

**Comment by migueln** [comment]
It seems that removing the docHistory and projectHistoryMetaData did the trick. Now the history of my broken document is empty, but if I make a couple of changes and save them, they appear as a new snapshot (as the first snapshot actually).

I revised my redis config and the snapshot options (both AOF and RDB) are apparently enabled, but being inside a docker container, it could happen that after a crash and a reboot of the whole container, some data was not fully committed to the db.

**Comment by henryoswald** [comment]
Good to hear you have it in a decent state.
