### ISSUE TITLE
Server crash after uploading zip project

### ISSUE THREAD

**Issue by tialis** [sharelatex/sharelatex#249]
Hi all, 

Our server crashes every time an user tries to upload a (relatively big) zip file with subfolders in it. 

Is it a known issue?

Cheers!

**Comment by henryoswald** [comment]
How big is big?

sent from my mobile.

**Comment by tialis** [comment]
24 MB

**Comment by henryoswald** [comment]
That should work. Do you have any errors?



On Wed, Jan 14, 2015 at 11:56 AM, tialis <notifications@github.com> wrote:

> 24 MB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/249#issuecomment-69906202>
> .
>



-- 
Henry Oswald
shareLaTeX.com creator

**Comment by tialis** [comment]
Sorry for the huge text, but I don't know if previous errors are relevant:


[2015-01-14T13:41:05.494Z] ERROR: web-sharelatex/54 on sharelatex: error passed to top level next middlewear (url=/project/53d65056e4f637e30ab030f9/settings, method=POST)
    Error: Forbidden
      at Object.exports.error (/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:116:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:106:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:312:9)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:329:9
      at /sharelatex/web/node_modules/connect-redis/lib/connect-redis.js:93:25
      at try_callback (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:522:9)
      at RedisClient.return_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:592:13)
      at RedisReplyParser.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:265:14)
      at RedisReplyParser.emit (events.js:95:17)
      at RedisReplyParser.send_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:281:18)
      at RedisReplyParser.execute (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:188:26)
      at RedisClient.on_data (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:478:27)
      at Socket.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:79:14)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
    
[2015-01-14T13:41:05.501Z] ERROR: web-sharelatex/54 on sharelatex: error passed to top level next middlewear (url=/user/settings, method=POST)
    Error: Forbidden
      at Object.exports.error (/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:116:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:106:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:312:9)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:329:9
      at /sharelatex/web/node_modules/connect-redis/lib/connect-redis.js:93:25
      at try_callback (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:522:9)
      at RedisClient.return_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:592:13)
      at RedisReplyParser.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:265:14)
      at RedisReplyParser.emit (events.js:95:17)
      at RedisReplyParser.send_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:281:18)
      at RedisReplyParser.execute (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:188:26)
      at RedisClient.on_data (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:478:27)
      at Socket.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:79:14)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
    
[2015-01-14T13:41:05.504Z] ERROR: web-sharelatex/54 on sharelatex: error passed to top level next middlewear (url=/project/53d65056e4f637e30ab030f9/settings, method=POST)
    Error: Forbidden
      at Object.exports.error (/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:116:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:106:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:312:9)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:329:9
      at /sharelatex/web/node_modules/connect-redis/lib/connect-redis.js:93:25
      at try_callback (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:522:9)
      at RedisClient.return_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:592:13)
      at RedisReplyParser.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:265:14)
      at RedisReplyParser.emit (events.js:95:17)
      at RedisReplyParser.send_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:281:18)
      at RedisReplyParser.execute (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:188:26)
      at RedisClient.on_data (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:478:27)
      at Socket.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:79:14)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
    
[2015-01-14T13:41:05.521Z] ERROR: web-sharelatex/54 on sharelatex: error passed to top level next middlewear (url=/project/53d65056e4f637e30ab030f9/settings, method=POST)
    Error: Forbidden
      at Object.exports.error (/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:116:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/sharelatex/web/app/js/infrastructure/Server.js:106:14)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at next (/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:312:9)
      at /sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:329:9
      at /sharelatex/web/node_modules/connect-redis/lib/connect-redis.js:93:25
      at try_callback (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:522:9)
      at RedisClient.return_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:592:13)
      at RedisReplyParser.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:265:14)
      at RedisReplyParser.emit (events.js:95:17)
      at RedisReplyParser.send_reply (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:281:18)
      at RedisReplyParser.execute (/sharelatex/web/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:188:26)
      at RedisClient.on_data (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:478:27)
      at Socket.<anonymous> (/sharelatex/web/node_modules/connect-redis/node_modules/redis/index.js:79:14)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
    
[2015-01-14T13:43:18.391Z]  INFO: web-sharelatex/54 on sharelatex: http request (response-time=1, req.remote-addr=127.0.0.1)
    GET / HTTP/1.1
    --
    req.user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
[2015-01-14T13:43:18.655Z]  INFO: web-sharelatex/54 on sharelatex: http request (response-time=250, req.remote-addr=127.0.0.1)
    GET /login HTTP/1.1
    --
    req.user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
[2015-01-14T13:43:27.742Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.users, response-time=2)
    query: {
      "email": "diegoherranz@fis.ucm.es"
    }
[2015-01-14T13:43:27.769Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=update, collection=sharelatex.users, response-time=3)
[2015-01-14T13:43:27.770Z]  INFO: web-sharelatex/54 on sharelatex: successful log in (email=diegoherranz@fis.ucm.es, user_id=53c3dbca7c7e0fd01700d959)
[2015-01-14T13:43:27.770Z]  INFO: web-sharelatex/54 on sharelatex: http request (response-time=39, req.referrer=http://duperier.gae.ucm.es:2000/login, req.remote-addr=127.0.0.1, req.content-length=99)
    POST /login HTTP/1.1
    --
    req.user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
[2015-01-14T13:43:27.788Z]  INFO: web-sharelatex/54 on sharelatex: checking if user has subscription (user_id=53c3dbca7c7e0fd01700d959)
[2015-01-14T13:43:27.788Z]  INFO: web-sharelatex/54 on sharelatex: getting users subscription (user_id=53c3dbca7c7e0fd01700d959)
[2015-01-14T13:43:27.792Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.projects, response-time=4)
    query: {
      "owner_ref": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:43:27.793Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.subscriptions, response-time=4)
    query: {
      "admin_id": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:43:27.795Z]  INFO: web-sharelatex/54 on sharelatex: checking if user has subscription (hasValidSubscription=false, subscription=null)
    user: {
      "id": "53c3dbca7c7e0fd01700d959",
      "email": "diegoherranz@fis.ucm.es"
    }
[2015-01-14T13:43:27.795Z]  INFO: web-sharelatex/54 on sharelatex: checking is user is member of subscription groups
[2015-01-14T13:43:27.795Z]  INFO: web-sharelatex/54 on sharelatex: getting users group subscriptions (user_id=53c3dbca7c7e0fd01700d959)
[2015-01-14T13:43:27.797Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.projects, response-time=3)
    query: {
      "collaberator_refs": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:43:27.798Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.subscriptions, response-time=2)
    query: {
      "member_ids": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:43:27.797Z]  INFO: tags-sharelatex/65 on sharelatex: getting user tags (user_id=53c3dbca7c7e0fd01700d959)
[2015-01-14T13:43:27.799Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.projects, response-time=1)
    query: {
      "readOnly_refs": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:43:27.800Z]  INFO: web-sharelatex/54 on sharelatex: checking if user has subscription or is group member (user_id=53c3dbca7c7e0fd01700d959, isMember=false, hasSubscription=false)
[2015-01-14T13:43:27.801Z]  INFO: tags-sharelatex/65 on sharelatex: mongo request (query_type=query, collection=sharelatex.tags, response-time=3)
    query: {
      "user_id": "53c3dbca7c7e0fd01700d959"
    }
null []
[2015-01-14T13:43:27.804Z]  INFO: web-sharelatex/54 on sharelatex: getting all tags from tags api (allTags=[], user_id=53c3dbca7c7e0fd01700d959, groupedByProject={})
[2015-01-14T13:43:27.804Z]  INFO: web-sharelatex/54 on sharelatex: rendering project list (user_id=53c3dbca7c7e0fd01700d959)
    results: {
      "hasSubscription": false,
      "projects": [
        [
          {
            "_id": "54b52efcd3e3ca35004643bd",
            "owner_ref": "53c3dbca7c7e0fd01700d959",
            "publicAccesLevel": "private",
            "lastUpdated": "2015-01-13T14:43:08.916Z",
            "name": "Test"
          },
          {
            "_id": "54b536fbd3e3ca35004643c2",
            "owner_ref": "53c3dbca7c7e0fd01700d959",
            "archived": true,
            "publicAccesLevel": "private",
            "lastUpdated": "2015-01-13T15:17:15.658Z",
            "name": "CentralPixelTDAS"
          },
          {
            "_id": "54b540c037a5545200a5063a",
            "owner_ref": "53c3dbca7c7e0fd01700d959",
            "archived": true,
            "publicAccesLevel": "private",
            "lastUpdated": "2015-01-13T15:58:56.865Z",
            "name": "CentralPixelTDAS"
          },
          {
            "_id": "54b541fe1ac86045006cb74e",
            "owner_ref": "53c3dbca7c7e0fd01700d959",
            "archived": true,
            "publicAccesLevel": "private",
            "lastUpdated": "2015-01-13T16:04:14.700Z",
            "name": "Central Pixel TDAS"
          }
        ],
        [],
        []
      ],
      "tags": [
        [],
        {}
      ]
    }
[2015-01-14T13:43:27.803Z]  INFO: tags-sharelatex/65 on sharelatex: http request (response-time=6, req.remote-addr=127.0.0.1)
    GET /user/53c3dbca7c7e0fd01700d959/tag HTTP/1.1
[2015-01-14T13:43:27.809Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.users, response-time=2)
    query: {
      "_id": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:43:28.308Z]  INFO: web-sharelatex/54 on sharelatex: http request (response-time=524, req.referrer=http://duperier.gae.ucm.es:2000/login, req.remote-addr=127.0.0.1)
    GET /project HTTP/1.1
    --
    req.user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
[2015-01-14T13:46:50.373Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query={}, query_type=query, collection=sharelatex.systemmessages, response-time=1)
[2015-01-14T13:46:50.375Z]  INFO: web-sharelatex/54 on sharelatex: creating blank project (owner_id=53c3dbca7c7e0fd01700d959, projectName="cpix tdas tom")
[2015-01-14T13:46:50.379Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=query, collection=sharelatex.users, response-time=1)
    query: {
      "_id": "53c3dbca7c7e0fd01700d959"
    }
[2015-01-14T13:46:50.386Z]  INFO: web-sharelatex/54 on sharelatex: mongo request (query_type=insert, collection=sharelatex.projects, response-time=2)
[2015-01-14T13:46:50.387Z]  INFO: web-sharelatex/54 on sharelatex: unzipping file
    source: /sharelatex/tmp/uploads/b0bd9cbcb9dca5425e0496952f8f5faa
    --
    destination: /sharelatex/tmp/uploads/b0bd9cbcb9dca5425e0496952f8f5faa-1421243210387
Exception: Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)

-> completed /sharelatex/web/app.js (357896ms)

>> 1 file and 0 calls executed (357901ms)

Done, without errors.
    
    
    Executing (default): SELECT * FROM `Projects` WHERE lastAccessed < '2015-01-13 13:50:55';
[2015-01-14T13:50:55.602Z]  INFO: clsi/60 on sharelatex: clearing expired projects
    project_ids: [
      "547ed5c9f2602d49005e3532",
      "54099bd200d5e8ef5a8cc005"
    ]
[2015-01-14T13:50:55.604Z]  INFO: clsi/60 on sharelatex: clearing project (project_id=547ed5c9f2602d49005e3532)
[2015-01-14T13:50:55.616Z] ERROR: clsi/60 on sharelatex: error clearing project (project_id=547ed5c9f2602d49005e3532)
    Error: rm -r /sharelatex/data/compiles/547ed5c9f2602d49005e3532 failed: rm: cannot remove '/sharelatex/data/compiles/547ed5c9f2602d49005e3532': No such file or directory
    
        at ChildProcess.<anonymous> (/sharelatex/clsi/app/js/CompileManager.js:85:27)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Socket.<anonymous> (child_process.js:979:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:466:12)
[2015-01-14T13:50:55.617Z]  INFO: clsi/60 on sharelatex: clearing project (project_id=54099bd200d5e8ef5a8cc005)
[2015-01-14T13:50:55.624Z] ERROR: clsi/60 on sharelatex: error clearing project (project_id=54099bd200d5e8ef5a8cc005)
    Error: rm -r /sharelatex/data/compiles/54099bd200d5e8ef5a8cc005 failed: rm: cannot remove '/sharelatex/data/compiles/54099bd200d5e8ef5a8cc005': No such file or directory
    
        at ChildProcess.<anonymous> (/sharelatex/clsi/app/js/CompileManager.js:85:27)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Socket.<anonymous> (child_process.js:979:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:466:12)

**Comment by tialis** [comment]
The server goes through a nginx to access through different ports, by the way...

**Comment by henryoswald** [comment]
There are a few problems in there but im not sure which one is todo with zips. Do the following work
- uploading small zips 
- upload image files
- compiles

**Comment by migueln** [comment]
Hi,

I'm one of the admins of the sharelatex instance tialis mentioned. There are still crashes from time to time when someone uploads a medium sized zip. Here's a more depurated log with the crash.

```
[2015-02-11T08:10:16.477Z]  INFO: web-sharelatex/66 on sharelatex: creating blank project (owner_id=XXX, projectName=XXX)
[2015-02-11T08:10:16.480Z]  INFO: web-sharelatex/66 on sharelatex: mongo request (query_type=query, collection=sharelatex.users, response-time=1)
    query: {
      "_id": "XXX"
    }
[2015-02-11T08:10:16.484Z]  INFO: web-sharelatex/66 on sharelatex: mongo request (query_type=insert, collection=sharelatex.projects, response-time=2)
[2015-02-11T08:10:16.485Z]  INFO: web-sharelatex/66 on sharelatex: unzipping file
    source: /sharelatex/tmp/uploads/XXX
    --
    destination: /sharelatex/tmp/uploads/XXX-YYY
Exception: Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)

-> completed /sharelatex/web/app.js (80203732ms)

>> 1 file and 0 calls executed (80203738ms)

Done, without errors.
```

So apparently the problem is not in the upload (the size in this case is only 7202043 bytes, far less than the 24mb tialis mentioned) but in the unzipping procedure, Am I wrong?

**Comment by jpallen** [comment]
The `ENOENT` (no entity error) suggests that maybe the `unzip` command is missing from your system. Can you check if that works? Do any zip uploads work? If not I suspect this is the cause.

This shouldn't crash on error here though, I notice that we're missing an error handler. I'll look into fixing that.

**Comment by migueln** [comment]
jpallen, you are right. We didn't install unzip. It seems to work flawlessly now. Thanks !!!

**Comment by jpallen** [comment]
Great!

**Comment by jpallen** [comment]
Fixed in sharelatex/web-sharelatex@62c4f23

**Comment by larissaleite** [comment]
Was this feature removed? I can't find the option upload a zip project anymore

**Comment by jpallen** [comment]
No, it should be an option in the 'New Project' menu.

**Comment by larissaleite** [comment]
Hi, @jpallen thanks for your answer. I just realized that in portuguese Upload is being translated as Update, that's why I thought it had been removed. When I changed to English, everything went back to normal. Cheers!
