### ISSUE TITLE
custom redis host

### ISSUE THREAD

**Issue by rubenmoor** [sharelatex/sharelatex#255]
Hey,

I am trying to make sharelatex run dockerized with redis in a container on its own. Are the following lines in `settings.coffee` sufficient for a proper redis configuration?

    module.exports =
        redis:
            web:
                host: "redis" # my custom host
                port: "6379"
                password: "" # nothing changed here

I get the following error upon `node sharelatex/web/app.js`

    Exception: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
        at RedisClient.on_error (/var/www/sharelatex/web/node_modules/redis/index.js:185:24)
        ...

**Comment by henryoswald** [comment]
sounds like a networking problem. If you run redis-cli from the ShareLaTeX container can you connection to redis.

**Comment by rubenmoor** [comment]
The following command, run from within the sharelatex container works:

    $ redis-cli -h redis ping
    PONG

The error message says `Redis connection to 127.0.0.1:6379 failed`, therefore I think it tries to connect to localhost instead of my redis container, linked as `redis`.

**Comment by jpallen** [comment]
Can you post a longer stack trace of the original error please? It's
possible something is connecting to redis that isn't using the 'web' config
block.

Have you check if the site works even with this error? If there is
something not using the 'web' block, it is likely not critical.

**Comment by rubenmoor** [comment]
Found the following in redis-sharelatex module, file `index.coffee`, https://github.com/sharelatex/redis-sharelatex/blob/master/index.coffee

    module.exports = RedisSharelatex =
	createClient: (opts = {port: 6379, host: "localhost"})->

Regarding the stacktrace: I'm not a node guy and I don't know how to create a stacktrace easily. But I'll go and try to figure it out ...

**Comment by rubenmoor** [comment]
This is what `console.log(new Error().stack` gives me:

Error
  at RedisClient.on_error (/var/www/sharelatex/web/node_modules/redis/index.js:184:17)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/redis/index.js:95:14)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickDomainCallback (node.js:463:13)

And this is the already as informative, full error message:

Exception: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
  at RedisClient.on_error (/var/www/sharelatex/web/node_modules/redis/index.js:186:24)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/redis/index.js:95:14)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickDomainCallback (node.js:463:13)

Now checking whether it runs regardlessly.

**Comment by rubenmoor** [comment]
I can't tell if the error regarding redis is to blaim, but it's not working and the redis error is my only hint atm:

    $ grunt run:all
    ...
    [2015-01-21T12:50:51.321Z]  INFO: web-sharelatex/56 on 0cb2932c47dc: info: socket.io started
    [2015-01-21T12:50:51.408Z]  INFO: web-sharelatex/56 on 0cb2932c47dc: web-sharelatex listening on port 3000
    [2015-01-21T12:50:51.408Z]  INFO: web-sharelatex/56 on 0cb2932c47dc: 300 sockets enabled Exception: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED at RedisClient.on_error (/var/www/sharelatex/web/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/redis/index.js:95:14)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
    -> completed /var/www/sharelatex/web/app.js (5250ms)
    >> 1 file and 0 calls executed (5253ms)
    Done, without errors.

But no ping at :3000.

Thanks for your help so far!

**Comment by henryoswald** [comment]
can you try changing your config to:

module.exports =
    redis:
        web:
            host: "redis" # my custom host
            port: "6379"
            password: "" # nothing changed here
       fairy:
            host: "redis" # my custom host
            port: "6379"
            password: "" # nothing changed here

**Comment by rubenmoor** [comment]
Awsome. That was it. Thanks!

2015-01-21 16:31 GMT+01:00 Henry Oswald <notifications@github.com>:

**Comment by henryoswald** [comment]
Great

On Wed, Jan 21, 2015 at 3:49 PM, rubenmoor <notifications@github.com> wrote:

> Awsome. That was it. Thanks!
>
> 2015-01-21 16:31 GMT+01:00 Henry Oswald <notifications@github.com>:
>
> > can you try changing your config to:
> >
> > module.exports =
> > redis:
> > web:
> > host: "redis" # my custom host
> > port: "6379"
> > password: "" # nothing changed here
> > fairy:
> > host: "redis" # my custom host
> > port: "6379"
> > password: "" # nothing changed here
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sharelatex/sharelatex/issues/255#issuecomment-70857820>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/255#issuecomment-70861381>
> .
>



-- 
Henry Oswald
shareLaTeX.com creator
