### ISSUE TITLE
Can't open/delete project

### ISSUE THREAD

**Issue by Kuree** [sharelatex/sharelatex#261]
I tried to setup Sharelatex on Ubuntu 14.04LTS. After installing all the dependences, I can access the web page. But it failed creating/deleting/opening a project. The error message is as follows:
```
{"name":"web-sharelatex","hostname":"sharelatex","pid":24164,"level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n  at errnoException (net.js:901:11)\n  at Object.afterConnect [as oncomplete] (net.js:892:19)\n","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"url":"http://localhost:3003/project/54d3bba9436280215e991b66/doc/54d3bba9436280215e991b67?fromVersion=-1","project_id":"54d3bba9436280215e991b66","doc_id":"54d3bba9436280215e991b67","msg":"error getting doc from doc updater","time":"2015-02-05T18:55:51.019Z","v":0}

```

I think the redis and mongodb are running with default port. All other dependencies' version are as follow:

```
sharelatex@sharelatex:/var/www/sharelatex$ latexmk -version
Latexmk, John Collins, 10 January 2015. Version 4.42
sharelatex@sharelatex:/var/www/sharelatex$ pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex)
 restricted \write18 enabled.

```

Any help will be appreciated.

**Comment by Kuree** [comment]
I removed the entire sharelatex files and re-installed it with deb package, which works. However, I got a compilation error when I tried to compile a tex file.

```
0 words of pdfTeX memory
0 indirect objects
No pages of output.
Transcript written on pdflatex.log.
fmtutil: /home/sharelatex/.texlive2014/texmf-var/web2c/pdftex/pdflatex.fmt installed.
fmtutil: No errors, exiting successfully.
---! /home/sharelatex/.texlive2014/texmf-var/web2c/pdftex/pdflatex.fmt doesn't match pdftex.pool
(Fatal format file error; I'm stymied)
Failure to make '/var/lib/sharelatex/data/compiles/54d3d98646d95dcc6b716985/output.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: (Pdf)LaTeX failed to generate the expected log file '/var/lib/sharelatex/data/compiles/54d3d98646d95dcc6b716985/output.log'
Latexmk: Did not finish processing file 'main.tex':
   (Pdf)LaTeX failed to generate the expected log file '/var/lib/sharelatex/data/compiles/54d3d98646d95dcc6b716985/output.log'
Latexmk: Undoing directory change
Latexmk: Errors, in force_mode: so I tried finishing targets
{"name":"clsi","hostname":"sharelatex","pid":752,"level":30,"project_id":"54d3d98646d95dcc6b716985","time_taken":4718,"msg":"done compile","time":"2015-02-05T21:10:05.775Z","v":0}

```

I can compile the same tex file using pdflatex command.

Any ideas? Thanks in advance.

**Comment by jpallen** [comment]
Hmm, I've never seen this before. It looks like an internal tex error. Does it work if you try with latexmk directly? Do you have the same PATH configured when you try it manually and when running the CLSI service?

**Comment by Kuree** [comment]
I've checked the path configuration. It turned out that I had two different tex systems on the server and it might cause the confusion for the CLSI service. After a clean re-install it finally works. Thank you very much!.

**Comment by jpallen** [comment]
Glad to hear you got it working!

**Comment by hulk1st** [comment]
Can you tell me where/how you changed it? I think I have exactly the same problem
