### ISSUE TITLE
 Exception: Error: connection closed

### ISSUE THREAD

**Issue by Buzzy0815** [sharelatex/sharelatex#263]
Hey,

I want to run sharelatex on my vServer running CentOS 6.6 64bit. I followed the instructions and even reinitialized the whole server once but without effort. `grunt check` runs fine. When I run `grunt run:web` I can access the webinterface with my browser but when I run `grunt -f` results in an error. Can anyone help me?

Here is the output of `grunt -f`:

```
Running "concurrent:all" (concurrent) task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task

Running "execute:real-time" (execute) task
-> executing /var/www/sharelatex/real-time/app.js

Running "execute:web" (execute) task
-> executing /var/www/sharelatex/web/app.js

Running "execute:track-changes" (execute) task
-> executing /var/www/sharelatex/track-changes/app.js

Running "execute:clsi" (execute) task
-> executing /var/www/sharelatex/clsi/app.js

Running "execute:document-updater" (execute) task
-> executing /var/www/sharelatex/document-updater/app.js

Running "execute:tags" (execute) task
-> executing /var/www/sharelatex/tags/app.js


Running "execute:chat" (execute) task
-> executing /var/www/sharelatex/chat/app.js
Running "execute:docstore" (execute) task
-> executing /var/www/sharelatex/docstore/app.js

Running "execute:filestore" (execute) task
-> executing /var/www/sharelatex/filestore/app.js

Running "execute:spelling" (execute) task
-> executing /var/www/sharelatex/spelling/app.js
[2015-02-12T10:48:02.652Z]  INFO: filestore/3441 on 123.onlinehome-server.info: Loading backend (backend=fs)
info: socket.io started
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Development Enviroment
Warning: -> error null /var/www/sharelatex/tags/app.js (13668ms) Used --force, continuing.

Warning:  Error Used --force, continuing.

Done, but with warnings.


    Warning: -> error null /var/www/sharelatex/docstore/app.js (13736ms) Used --force, continuing.

Warning:  Error Used --force, continuing.

Done, but with warnings.


    Warning: -> error null /var/www/sharelatex/filestore/app.js (13782ms) Used --force, continuing.

Warning:  Error: connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0 Used --force, continuing.

Done, but with warnings.


    info: socket.io started
Warning: -> error null /var/www/sharelatex/spelling/app.js (14356ms) Used --force, continuing.

Warning:  Error Used --force, continuing.

Done, but with warnings.


    [2015-02-12T10:48:10.797Z]  INFO: track-changes/3415 on 123.onlinehome-server.info: track changes api listening on http://localhost:3015
Development Enviroment
[2015-02-12T10:48:10.952Z]  INFO: chat-sharelatex/3435 on 123.onlinehome-server.info: chat-sharelatex listening on localhost:3010
[2015-02-12T10:48:11.012Z]  INFO: clsi/3419 on 123.onlinehome-server.info: CLSI listening on localhost:3013
[2015-02-12T10:48:11.217Z]  INFO: documentupdater/3423 on 123.onlinehome-server.info: documentupdater-sharelatex server listening on port 3003
[2015-02-12T10:48:11.369Z]  INFO: real-time-sharelatex/3409 on 123.onlinehome-server.info: real-time-sharelatex listening on localhost:3026
[2015-02-12T10:48:11.611Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: Generating file fingerprints...
[2015-02-12T10:48:11.628Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/require.js: 0cb51c1a5e8e978cbe069c07f3b8d16d
[2015-02-12T10:48:11.630Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/ide.js: 30ebf924305ccca856b2c84d2bf27619
[2015-02-12T10:48:11.631Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/main.js: e656200639caa7b9d022885f738e8ab2
[2015-02-12T10:48:11.631Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs.js: 099e314d2df740430b1d0679a06d5a71
[2015-02-12T10:48:11.637Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/ace/ace.js: 036843c1b38dde38d79d6bc5e71d1948
[2015-02-12T10:48:11.639Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/pdf.js: 39877fdae4da632887722daaa37fddde
[2015-02-12T10:48:11.646Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/pdf.worker.js: ada321e71bb42760507a9ef25c83797e
[2015-02-12T10:48:11.647Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/compatibility.js: 528166dee08e84d2f1564a14013f1a58
[2015-02-12T10:48:11.649Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/pdfjs-1.0.712/pdf.js: 92166e6b2d08654676b0d8cd9626e3bf
[2015-02-12T10:48:11.663Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/pdfjs-1.0.712/pdf.worker.js: 210811c9e9352ad6a85d17bd9fec15ce
[2015-02-12T10:48:11.665Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/js/libs/pdfjs-1.0.712/compatibility.js: b77271860c12ab8774593f7aee8e6dbf
[2015-02-12T10:48:11.667Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: /var/www/sharelatex/web/public/stylesheets/style.css: cadeda1f057e42984029c3c1212e7f93
[2015-02-12T10:48:14.557Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info:
[2015-02-12T10:48:14.600Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: web-sharelatex listening on port 3000
[2015-02-12T10:48:14.612Z]  INFO: web-sharelatex/3417 on 123.onlinehome-server.info: 300 sockets enabled
Exception: Error: connection closed
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:605:24)
  at [object Object].emit (events.js:92:17)
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:155:15)
  at [object Object].emit (events.js:98:17)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:528:12)
  at Socket.emit (events.js:95:17)
  at TCP.close (net.js:466:12)
```

**Comment by jpallen** [comment]
Can you try a clean run with `killall node` and then `grunt run:all` please? It looks like the web process is having trouble talking to MongoDB - do you have this running and can access it locally ok?

**Comment by Buzzy0815** [comment]
thanks for your help!
`killall node` says no processes killed.
`grunt run:all` gets the connect 3.0 warning and cancels therefore.
I did a reboot and then a `grunt run:all -f` with the same error as above.

**Comment by jpallen** [comment]
The `Error connection closed` is from talking to MongoDB. Can you check the mongo logs and whether it's all running correctly?

**Comment by Buzzy0815** [comment]
mongod.log says :
```
2015-02-12T12:04:30.971+0100 [initandlisten] pthread_create failed: errno:11 Resource temporarily unavailable
2015-02-12T12:04:30.971+0100 [initandlisten] can't create new thread, closing connection
```

**Comment by jpallen** [comment]
It looks like that's where the problem is. I'm sorry I don't know enough about Mongo to know the underlying cause, but it should be something you can search for/ask on the mongo lists.

**Comment by Buzzy0815** [comment]
okay I will search for this error and ask there... thanks for your help!

**Comment by Buzzy0815** [comment]
I asked the question on stackoverflow:
http://stackoverflow.com/questions/28477997/mongodb-pthread-create-failed-errno11
