### ISSUE TITLE
Upgrade to v0.1.3 failed

### ISSUE THREAD

**Issue by rdissauer** [sharelatex/sharelatex#276]
I upgraded to v0.1.3 today by following the wiki update entry and the v0.1.2 release notes without errors. After config changes of nginx i restarted nginx and started all sharelatex services again. Login works great but when i open any project I get an error
'Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.'
The editor also doesn't load.

Can anyone please point me to the right direction?

Here the log output:
```
==> /var/log/sharelatex/web.log <==

{"message":"Forbidden","name":"Error","stack":"Error: Forbidden
  at Object.exports.error (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
  at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
  at Object.handle (/var/www/html/sharelatex/web/app/js/infrastructure/Server.js:116:14)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.handle (/var/www/html/sharelatex/web/app/js/infrastructure/Server.js:106:14)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.session [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:301:7)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.cookieParser [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.setLangBasedOnDomainMiddlewear [as handle] (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/app/coffee/translations.coffee:33:4)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at /var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/i18next.js:111:13
  at /var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/dep/i18next.js:971:21
  at Object.i18n.functions.extend.load (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/i18nextWrapper.js:290:17)
  at init (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/dep/i18next.js:967:19)
  at Object.setLng (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/dep/i18next.js:1157:16)
  at Object.i18n.handle (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/i18next.js:109:14)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at multipart (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
  at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
  at urlencoded (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
  at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
  at json (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
  at Object.bodyParser [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at multipart (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
  at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
  at urlencoded (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
  at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
  at json (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
  at Object.bodyParser [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.staticMiddleware [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/static.js:55:61)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.expressInit [as handle] (/var/www/html/sharelatex/web/node_modules/express/lib/middleware.js:30:5)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.query [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
  at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Function.app.handle (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:198:3)
  at Server.app (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/connect.js:65:37)
  at Manager.handleRequest (/var/www/html/sharelatex/web/node_modules/socket.io/lib/manager.js:565:28)
  at Server.<anonymous> (/var/www/html/sharelatex/web/node_modules/socket.io/lib/manager.js:119:10)
  at Server.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2112:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1970:22)
  at TCP.onread (net.js:527:27)
","status":403},"url":"/project/54f438a42d4c5a3e39b0ae82/join?user_id=545788940f608c8d21114bd4","method":"POST","msg":"error passed to top level next middlewear","time":"2015-03-02T11:01:45.518Z","v":0}

==> /var/log/sharelatex/real-time.log <==
{"message":"non-success status code from web: 403","name":"Error","stack":"Error: non-success status code from web: 403
  at Request._callback (/var/www/html/sharelatex/real-time/app/js/WebApiManager.js:41:17)
  at Request.self.callback (/var/www/html/sharelatex/real-time/node_modules/request/request.js:121:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:978:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:929:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
"},"project_id":"54f438a42d4c5a3e39b0ae82","user_id":"545788940f608c8d21114bd4","msg":"error accessing web api","time":"2015-03-02T11:01:45.520Z","v":0}
"level":50,"project_id":"54f438a42d4c5a3e39b0ae82","doc_id":null,"client_id":"K4pRQ3QC32GYLE1b3662","err":{"message":"non-success status code from web: 403","name":"Error","stack":"Error: non-success status code from web: 403
  at Request._callback (/var/www/html/sharelatex/real-time/app/js/WebApiManager.js:41:17)
  at Request.self.callback (/var/www/html/sharelatex/real-time/node_modules/request/request.js:121:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:978:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:929:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
"},"msg":"server side error in joinProject","time":"2015-03-02T11:01:45.521Z","v":0}


==> /var/log/sharelatex/clsi.log <==
Executing (default): SELECT * FROM `Projects` WHERE `Projects`.`project_id`='54f438a42d4c5a3e39b0ae82' LIMIT 1;
Executing (default): UPDATE `Projects` SET `project_id`='54f438a42d4c5a3e39b0ae82',`lastAccessed`='2015-03-02 11:01:45',`id`=33,`createdAt`='2015-03-02 10:17:09',`updatedAt`='2015-03-02 11:01:45' WHERE `id`=33
"level":30,"project_id":"54f438a42d4c5a3e39b0ae82","msg":"starting compile","time":"2015-03-02T11:01:45.824Z","v":0}
"level":30,"project_id":"54f438a42d4c5a3e39b0ae82","time_taken":23,"msg":"written files to disk","time":"2015-03-02T11:01:45.847Z","v":0}
"level":30,"directory":"/var/lib/sharelatex/data/compiles/54f438a42d4c5a3e39b0ae82","compiler":"pdflatex","timeout":60000,"mainFile":"main.tex","msg":"starting compile","time":"2015-03-02T11:01:45.849Z","v":0}
"level":30,"project_id":"54f438a42d4c5a3e39b0ae82","command":["latexmk","-cd","-f","-jobname=output","-auxdir=/var/lib/sharelatex/data/compiles/54f438a42d4c5a3e39b0ae82","-outdir=/var/lib/sharelatex/data/compiles/54f438a42d4c5a3e39b0ae82","-pdf","-e","$pdflatex='pdflatex -synctex=1 -interaction=batchmode %O %S'","/var/lib/sharelatex/data/compiles/54f438a42d4c5a3e39b0ae82/main.tex"],"directory":"/var/lib/sharelatex/data/compiles/54f438a42d4c5a3e39b0ae82","msg":"running command","time":"2015-03-02T11:01:45.850Z","v":0}
"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2015-03-02T11:01:45.850Z","v":0}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

==> /var/log/sharelatex/web.log <==
"level":50,"err":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up
  at createHangUpError (http.js:1476:15)
  at Socket.socketOnEnd [as onend] (http.js:1572:23)
  at Socket.g (events.js:180:16)
  at Socket.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
","code":"ECONNRESET"},"url":"/project/54f438a42d4c5a3e39b0ae82/compile?auto_compile=true","method":"POST","msg":"error passed to top level next middlewear","time":"2015-03-02T11:01:45.861Z","v":0}

```

**Comment by henryoswald** [comment]
Can you check all services are running including redis. Clearing your cookies could also help.

**Comment by rdissauer** [comment]
I cleared all my cookies and checked following services:

redis, mongodb, sharelatex- web, track-changes, tags, spelling, real-time, filestore, document-updater, docstore, clsi

all services are running.

**Comment by rdissauer** [comment]
Here is a screenshot of my project:
![bildschirmfoto 2015-03-02 um 13 16 47](https://cloud.githubusercontent.com/assets/1752433/6440583/a01da21a-c0de-11e4-8149-28bdb3258cad.png)

**Comment by rdissauer** [comment]
I still don't find the issue... i'm going crazy with this...

`grunt check --force` as user sharelatex delivers following:
```
Running "check:redis" task
Checking Redis is running... OK.
Running Redis version 2.8.14

Running "check:latexmk" task
Checking latexmk is installed... OK.
Running latexmk version 4.39

Running "check:s3" task
Filestore other than S3 configured. Not checking S3.

Running "check:fs" task
Checking FS configuration... OK.

Running "check:aspell" task
Checking aspell is installed... OK.
The following spell check dictionaries are available:
de
de_AT
de_CH
de_DE
en
en-variant_0
en-variant_1
en-variant_2
en-w_accents
en-wo_accents
en_CA
en_CA-variant_0
en_CA-variant_1
en_CA-w_accents
en_CA-wo_accents
en_GB
en_GB-ise
en_GB-ise-w_accents
en_GB-ise-wo_accents
en_GB-ize
en_GB-ize-w_accents
en_GB-ize-wo_accents
en_GB-variant_0
en_GB-variant_1
en_GB-w_accents
en_GB-wo_accents
en_US
en_US-variant_0
en_US-variant_1
en_US-w_accents
en_US-wo_accents

Done, without errors.
```

`grunt test:unit` as user sharelatex delivers `Done, without errors` on all services including new real-time service.

`grunt run:all` as user sharelatex starts all services without any error.

log into webinterface completes without any error.

creating a new project completes without any error.

project opens automatically and following errors appear:

```
[2015-03-03T13:43:09.891Z] ERROR: web-sharelatex/7300 on <server>: error passed to top level next middlewear (method=POST)
    Error: Forbidden
      at Object.exports.error (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
      at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
      at Object.handle (/var/www/html/sharelatex/web/app/js/infrastructure/Server.js:116:14)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/var/www/html/sharelatex/web/app/js/infrastructure/Server.js:106:14)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.session [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:301:7)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.cookieParser [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.setLangBasedOnDomainMiddlewear [as handle] (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/app/coffee/translations.coffee:33:4)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at /var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/i18next.js:111:13
      at /var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/dep/i18next.js:971:21
      at Object.i18n.functions.extend.load (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/i18nextWrapper.js:290:17)
      at init (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/dep/i18next.js:967:19)
      at Object.setLng (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/dep/i18next.js:1157:16)
      at Object.i18n.handle (/var/www/html/sharelatex/web/node_modules/translations-sharelatex/node_modules/i18next/lib/i18next.js:109:14)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at multipart (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
      at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
      at urlencoded (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
      at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
      at json (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
      at Object.bodyParser [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at multipart (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
      at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
      at urlencoded (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
      at /var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
      at json (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
      at Object.bodyParser [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.staticMiddleware [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/static.js:55:61)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.expressInit [as handle] (/var/www/html/sharelatex/web/node_modules/express/lib/middleware.js:30:5)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.query [as handle] (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
      at next (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Function.app.handle (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:198:3)
      at Server.app (/var/www/html/sharelatex/web/node_modules/express/node_modules/connect/lib/connect.js:65:37)
      at Manager.handleRequest (/var/www/html/sharelatex/web/node_modules/socket.io/lib/manager.js:565:28)
      at Server.<anonymous> (/var/www/html/sharelatex/web/node_modules/socket.io/lib/manager.js:119:10)
      at Server.emit (events.js:98:17)
      at HTTPParser.parser.onIncoming (http.js:2112:12)
      at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
      at Socket.socket.ondata (http.js:1970:22)
      at TCP.onread (net.js:527:27)
    
    --
    url: /project/54f5b98aa2a46c841c5db443/join?user_id=545788940f608c8d21114bd4
[2015-03-03T13:43:09.886Z]  INFO: real-time-sharelatex/7329 on <server>: user joining project (user_id=545788940f608c8d21114bd4, project_id=54f5b98aa2a46c841c5db443, client_id=wxB_gnI-bDvmxkro2Mhv)
Executing (default): SELECT * FROM `Projects` WHERE `Projects`.`project_id`='54f5b98aa2a46c841c5db443' LIMIT 1;
Executing (default): UPDATE `Projects` SET `project_id`='54f5b98aa2a46c841c5db443',`lastAccessed`='2015-03-03 13:43:09',`id`=3,`createdAt`='2015-03-03 13:39:27',`updatedAt`='2015-03-03 13:43:09' WHERE `id`=3
[2015-03-03T13:43:09.887Z]  INFO: real-time-sharelatex/7329 on <server>: sending join project request to web (project_id=54f5b98aa2a46c841c5db443, user_id=545788940f608c8d21114bd4)
[2015-03-03T13:43:09.893Z] ERROR: real-time-sharelatex/7329 on <server>: error accessing web api (project_id=54f5b98aa2a46c841c5db443, user_id=545788940f608c8d21114bd4)
    Error: non-success status code from web: 403
      at Request._callback (/var/www/html/sharelatex/real-time/app/js/WebApiManager.js:41:17)
      at Request.self.callback (/var/www/html/sharelatex/real-time/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)
    
[2015-03-03T13:43:09.917Z]  INFO: documentupdater/7319 on <server>: flushing project via http (project_id=54f5b98aa2a46c841c5db443)
[2015-03-03T13:43:09.905Z]  INFO: web-sharelatex/7300 on <server>: mongo request (query_type=query, collection=sharelatex.projects, response-time=1)
    query: {
      "_id": "54f5b98aa2a46c841c5db443"
    }
[2015-03-03T13:43:09.926Z]  INFO: docstore/7330 on <server>: getting all docs (project_id=54f5b98aa2a46c841c5db443)
[2015-03-03T13:43:09.894Z] ERROR: real-time-sharelatex/7329 on <server>: server side error in joinProject (project_id=54f5b98aa2a46c841c5db443, doc_id=null, client_id=wxB_gnI-bDvmxkro2Mhv)
    Error: non-success status code from web: 403
      at Request._callback (/var/www/html/sharelatex/real-time/app/js/WebApiManager.js:41:17)
      at Request.self.callback (/var/www/html/sharelatex/real-time/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/var/www/html/sharelatex/real-time/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)
```

thank you in advance for any help!

**Comment by jpallen** [comment]
How have you got the config file for web and real-time set up? Can you check that real-time has the same httpAuth credentials that web is configured with? It sounds like real-time is being rejected when trying to connect to the web process to get the project details.

**Comment by rdissauer** [comment]
thanks for your hint, it seems like this is similar to issue #278 
is there any documentation about setting config options in `sharelatex/web/config` and `sharelatex/real-time/config/`? I thought that my `/etc/sharelatex/settings.coffee` i got from `sharelatex/config/` is the one and only config file.

**Comment by jpallen** [comment]
What do you have configured for the `apis.web.url` setting? Is it localhost, or a public host? I'm wondering if there might be some issue here with the CSRF token rejecting the internal request (it shouldn't). This might be related to whether it's a local request or not.

**Comment by rdissauer** [comment]
config file defined in `SHARELATEX_CONFIG` environment variable:
```
apis:
                web:
                        url: "http://localhost:3000"
                        user: httpAuthUser
                        pass: httpAuthPass
```
do sharelatex services use their own `settings.default.coffee` files from `sharelatex/<service>/config` or do they all use the same config file set in environment variable `SHARELATEX_CONFIG`?

**Comment by jpallen** [comment]
They use their own defaults file, but any settings in `SHARELATEX_CONFIG` will override these. Are you running the 0.1.3 version of web as well? Can you check that it is up to date please. If you're unsure, please post the contents of your `sharelatex/web/app/coffee/Features/Editor/EditorRouter.coffee`

**Comment by rdissauer** [comment]
`git pull` says `Already up-to-date` but the file mentioned does not exist. Following files are in this directory `sharelatex/web/app/coffee/Features/Editor/`:
EditorController.coffee
EditorHttpController.coffee
EditorRealTimeController.coffee
EditorUpdatesController.coffee

**Comment by jpallen** [comment]
Ok, I think you're still running and older (and incompatible) version of web. Can you go to the sharelatex/ directory, make sure you checkout version 0.1.3 (or the latest release branch), and then run `grunt update:all`

**Comment by rdissauer** [comment]
to get 0.1.3 i did following documented in "Update" wiki site:
```
sudo git pull 
sudo npm install
sudo grunt install
```

grunt update:all did the trick!

now, before the editor is loaded I get this:

![bildschirmfoto 2015-03-03 um 15 58 10](https://cloud.githubusercontent.com/assets/1752433/6465109/25c69076-c1bf-11e4-87a6-5471e253d941.png)

**Comment by jpallen** [comment]
Ok, now can you check that you have `websocketsUrl` set correctly in your config file? This should be set to the url that you use to access ShareLaTeX publicly. It should be explained in the release notes.

**Comment by rdissauer** [comment]
thank you very much! I had `websocketsUrl` set as mentioned in the release notes but I set `http://<my server>` instead of `https://<my server>`.
Now it works like a charm! Cheers!

**Comment by jpallen** [comment]
Glad you got it working! Is there anything we could have added/changed in the docs that would have made this easier?

**Comment by rdissauer** [comment]
a little bit more information on the upgrade procedure would be nice. At least the information of `grunt update:all` would help a lot since following documented commands don't do the trick.
´´´
git pull
npm install
grunt install
```
https://github.com/sharelatex/sharelatex/wiki/Updating

Thanks again for your help! This is an awesome project!!

**Comment by jpallen** [comment]
Thanks, I've updated that page (it was written by a third party it looks like, sorry for the confusion).
