### ISSUE TITLE
sharelatex crashes randomly

### ISSUE THREAD

**Issue by bauerj** [sharelatex/sharelatex#279]
After a few hours, sharelatex crashes with the following message:

    events.js:72
    	throw er; // Unhandled 'error' event
    		      ^
    	Error: This socket is closed.
    	    at Socket._write (net.js:637:19)
    	    at doWrite (_stream_writable.js:226:10)
    	    at writeOrBuffer (_stream_writable.js:216:5)
    	    at Socket.Writable.write (_stream_writable.js:183:11)
    	    at Socket.write (net.js:615:40)
    	    at SyncWriteStream.process.stdout.write (/var/www/sharelatex/node_modules/grunt-bunyan/tasks/bunyan.js:65:31)
    	    at Log._write (/var/www/sharelatex/node_modules/grunt/node_modules/grunt-legacy-log/index.js:159:26)
    	    at Log.bound [as _write] (/var/www/sharelatex/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/lodash/dist/lodash.js:729:21)
    	    at Log._writeln (/var/www/sharelatex/node_modules/grunt/node_modules/grunt-legacy-log/index.js:164:8)
    	    at Log.bound [as _writeln] (/var/www/sharelatex/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/lodash/dist/lodash.js:729:21)
    	    at Log.writeln (/var/www/sharelatex/node_modules/grunt/node_modules/grunt-legacy-log/index.js:175:8)
    	    at Log.bound [as writeln] (/var/www/sharelatex/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/lodash/dist/lodash.js:729:21)
    	    at writeln (/var/www/sharelatex/node_modules/grunt/lib/grunt/fail.js:39:13)
    	    at Object.fail.fatal (/var/www/sharelatex/node_modules/grunt/lib/grunt/fail.js:55:3)
    	    at process.uncaughtHandler (/var/www/sharelatex/node_modules/grunt/lib/grunt.js:130:10)
    	    at process.emit (events.js:95:17)
    	    at process._fatalException (node.js:272:26)

**Comment by Darxo** [comment]
I have the same problem. We worked with 3 guys at the same time when that happened last time. The Error Code was the same. The Same.

**Comment by jpallen** [comment]
Which process is this happening in? Can you post some more context from the logs please, and what you were doing when this happened?

**Comment by bauerj** [comment]
Well, the output above is what was printed in stderr by `grunt run`.

I guess the `document-updater` crashed because I can't find it in the process list anymore. 

I can't really say what exactly happened before the crash as I currently don't have any logging enabled.

**Comment by jpallen** [comment]
Thanks for the update. I'm afraid we'll need some logs before the crash if we're going to be able to debug this.
