### ISSUE TITLE
PDF preview does not work: requires convert from imagemagick and optipng

### ISSUE THREAD

**Issue by gentakojima** [sharelatex/sharelatex#297]
I'm running 0.13 and I've found that, when I upload a file, the PNG files can be previewed properly, but PDF files don't.

![screenshot](https://cloud.githubusercontent.com/assets/2670279/7163455/71a9b37c-e39a-11e4-9ffc-5c0b0c61dfd1.png)

I noticed that `?format=png` is attached at the end. If I try to load that URL alone, it just gives me the same 500 error. But if I remove the `?format=png` the file just loads fine.

I see this in the logs:

```{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"key":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","bucket":"/var/lib/sharelatex/data/user_files","format":"png","msg":"reciving request to get file","time":"2015-04-15T16:10:40.327Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"bucket":"/var/lib/sharelatex/data/user_files","key":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","opts":{"format":"png"},"msg":"getting file","time":"2015-04-15T16:10:40.327Z","v":0}
{"name":"5515467219a94e06046d5ea6_552e88eb71a028a403d9414b-converted-cache_format-png","hostname":"i-5-233-VM","pid":936,"level":30,"location":"/var/lib/sharelatex/data/user_files","msg":"checking if file exists","time":"2015-04-15T16:10:40.327Z","v":0}
{"name":"5515467219a94e06046d5ea6_552e88eb71a028a403d9414b-converted-cache_format-png","hostname":"i-5-233-VM","pid":936,"level":30,"location":"/var/lib/sharelatex/data/user_files","exists":false,"msg":"checked if file exists","time":"2015-04-15T16:10:40.328Z","v":0}
{"name":"5515467219a94e06046d5ea6_552e88eb71a028a403d9414b","hostname":"i-5-233-VM","pid":936,"level":30,"location":"/var/lib/sharelatex/data/user_files","msg":"getting file","time":"2015-04-15T16:10:40.329Z","v":0}
/var/lib/sharelatex/tmp/uploads 5515467219a94e06046d5ea6-552e88eb71a028a403d9414b
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","msg":"writing file locally","time":"2015-04-15T16:10:40.330Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","msg":"finished writing file locally","time":"2015-04-15T16:10:40.335Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"sourcePath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","requestedFormat":"png","msg":"converting file format","time":"2015-04-15T16:10:40.335Z","v":0}
nice convert -define pdf:fit-page=600x -flatten -density 300 /var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b[0] /var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b.png
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":50,"err":{"message":"Command failed: nice: convert: No such file or directory\n","name":"Error","stack":"Error: Command failed: nice: convert: No such file or directory\n\n    at ChildProcess.exithandler (child_process.js:648:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:756:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:823:5)","killed":false,"code":127,"signal":null},"stderr":"nice: convert: No such file or directory\n","sourcePath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b[0]","requestedFormat":"png","destPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b.png","msg":"something went wrong converting file","time":"2015-04-15T16:10:40.352Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":50,"err":{"message":"Command failed: nice: convert: No such file or directory\n","name":"Error","stack":"Error: Command failed: nice: convert: No such file or directory\n\n    at ChildProcess.exithandler (child_process.js:648:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:756:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:823:5)","killed":false,"code":127,"signal":null},"bucket":"/var/lib/sharelatex/data/user_files","origonalKey":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","opts":{"format":"png"},"msg":"error converting file","time":"2015-04-15T16:10:40.353Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":50,"err":{"message":"Command failed: nice: convert: No such file or directory\n","name":"Error","stack":"Error: Command failed: nice: convert: No such file or directory\n\n    at ChildProcess.exithandler (child_process.js:648:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:756:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:823:5)","killed":false,"code":127,"signal":null},"key":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","bucket":"/var/lib/sharelatex/data/user_files","format":"png","msg":"problem getting file","time":"2015-04-15T16:10:40.354Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"req":{"url":"/project/5515467219a94e06046d5ea6/file/552e88eb71a028a403d9414b?format=png","method":"GET","remote-addr":"127.0.0.1","content-length":"0"},"res":{"statusCode":500},"response-time":28,"msg":"http request","time":"2015-04-15T16:10:40.355Z","v":0}
```

It seems that convert from imagemagick is required. After installing imagemagick, it still doesn't work:

```{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"key":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","bucket":"/var/lib/sharelatex/data/user_files","format":"png","msg":"reciving request to get file","time":"2015-04-15T16:13:53.983Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"bucket":"/var/lib/sharelatex/data/user_files","key":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","opts":{"format":"png"},"msg":"getting file","time":"2015-04-15T16:13:53.983Z","v":0}
{"name":"5515467219a94e06046d5ea6_552e88eb71a028a403d9414b-converted-cache_format-png","hostname":"i-5-233-VM","pid":936,"level":30,"location":"/var/lib/sharelatex/data/user_files","msg":"checking if file exists","time":"2015-04-15T16:13:53.983Z","v":0}
{"name":"5515467219a94e06046d5ea6_552e88eb71a028a403d9414b-converted-cache_format-png","hostname":"i-5-233-VM","pid":936,"level":30,"location":"/var/lib/sharelatex/data/user_files","exists":false,"msg":"checked if file exists","time":"2015-04-15T16:13:53.984Z","v":0}
{"name":"5515467219a94e06046d5ea6_552e88eb71a028a403d9414b","hostname":"i-5-233-VM","pid":936,"level":30,"location":"/var/lib/sharelatex/data/user_files","msg":"getting file","time":"2015-04-15T16:13:53.985Z","v":0}
/var/lib/sharelatex/tmp/uploads 5515467219a94e06046d5ea6-552e88eb71a028a403d9414b
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","msg":"writing file locally","time":"2015-04-15T16:13:53.985Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","msg":"finished writing file locally","time":"2015-04-15T16:13:53.992Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"sourcePath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","requestedFormat":"png","msg":"converting file format","time":"2015-04-15T16:13:53.992Z","v":0}
nice convert -define pdf:fit-page=600x -flatten -density 300 /var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b[0] /var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b.png
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"sourcePath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b[0]","requestedFormat":"png","destPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b.png","msg":"finished converting file","time":"2015-04-15T16:14:00.108Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b","msg":"removing local temp file","time":"2015-04-15T16:14:00.108Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"localPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b.png","msg":"optimising png path","time":"2015-04-15T16:14:00.109Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":50,"err":{"message":"Command failed: /bin/sh: 1: optipng: not found\n","name":"Error","stack":"Error: Command failed: /bin/sh: 1: optipng: not found\n\n    at ChildProcess.exithandler (child_process.js:648:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:756:16)\n    at Socket.<anonymous> (child_process.js:969:11)\n    at Socket.emit (events.js:95:17)\n    at Pipe.close (net.js:465:12)","killed":false,"code":127,"signal":null},"stderr":"/bin/sh: 1: optipng: not found\n","localPath":"/var/lib/sharelatex/tmp/uploads/5515467219a94e06046d5ea6-552e88eb71a028a403d9414b.png","msg":"something went wrong converting compressPng","time":"2015-04-15T16:14:00.120Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":50,"err":{"message":"Command failed: /bin/sh: 1: optipng: not found\n","name":"Error","stack":"Error: Command failed: /bin/sh: 1: optipng: not found\n\n    at ChildProcess.exithandler (child_process.js:648:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:756:16)\n    at Socket.<anonymous> (child_process.js:969:11)\n    at Socket.emit (events.js:95:17)\n    at Pipe.close (net.js:465:12)","killed":false,"code":127,"signal":null},"key":"5515467219a94e06046d5ea6/552e88eb71a028a403d9414b","bucket":"/var/lib/sharelatex/data/user_files","format":"png","msg":"problem getting file","time":"2015-04-15T16:14:00.121Z","v":0}
{"name":"filestore","hostname":"i-5-233-VM","pid":936,"level":30,"req":{"url":"/project/5515467219a94e06046d5ea6/file/552e88eb71a028a403d9414b?format=png","method":"GET","remote-addr":"127.0.0.1","content-length":"0"},"res":{"statusCode":500},"response-time":6143,"msg":"http request","time":"2015-04-15T16:14:00.124Z","v":0}
```

It seems that optipng is also required. After installing optipng, it started working properly.

But neither imagemagick nor optipng are listed as dependencies here: https://github.com/sharelatex/sharelatex/wiki/Dependencies

Maybe you should add them as dependencies on the docs?

**Comment by jpallen** [comment]
Thanks, I've updated the docs now.

**Comment by gentakojima** [comment]
I think that you should also add this information to the main README.md to avoid confusion. Or avoid the duplication of information and redirect to the wiki for further instructions. 

I mean this file:
https://github.com/sharelatex/sharelatex/blob/master/README.md
