### ISSUE TITLE
Exception: Error: Cannot find module 'archiver'

### ISSUE THREAD

**Issue by egeu5** [sharelatex/sharelatex#308]
I just install sharelatex on Ubuntu Server 14.04. Everything seems to work fine but after starting there is no site at localhost:3000. If I start it something go wrong 

After a few Info-Lines I get 
Exception: Error: Cannot find module 'archiver'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/opt/sharelatex/web/app/js/Features/Downloads/ProjectZipStreamManager.js:4:14)
  at Object.<anonymous> (/opt/sharelatex/web/app/js/Features/Downloads/ProjectZipStreamManager.js:180:4)
  at Module._compile (module.js:456:26)
......
  at node.js:935:3

-> completed /opt/sharelatex/web/app.js (234812ms)

>> 1 file and 0 calls executed (234913ms)

Done, without errors.
    
Executing (default): SELECT * FROM `Projects` WHERE lastAccessed < '2015-05-01 16:48:08';
[2015-05-02T16:48:08.792Z]  INFO: clsi/14500 on vserver: clearing expired projects (project_ids=[])

There are no log files at /var/log/sharelatex so I don't know how to get more infos about the issue.

**Comment by egeu5** [comment]
Because of no reply for 12 days I tried a lot of different solutions. I am not shure what was right, but I think there were ownership-errors.

**Comment by Prabhat36** [comment]
same problem here.. any1 help
