### ISSUE TITLE
Error when opening Sharelatex Help Guide page

### ISSUE THREAD

**Issue by dpasqualin** [sharelatex/sharelatex#324]
When trying to open the Sharelatex Help Guide page I get the following error on my browser:

```
Oops, something went wrong with your request, sorry. If this continues, please contact us at foo@bar.com
```

The application server shows me this:
```
[2015-06-01T12:38:32.620Z] ERROR: web-sharelatex/18017 on sharelatex: error passed to top level next middlewear (url=/learn, method=GET)
    TypeError: Cannot read property 'requireLogin' of undefined
      at Object.module.exports.WikiController._checkIfLoginIsNeeded (/home/sharelatex/sharelatex/web/app/js/Features/Wiki/WikiController.js:20:29)
...
```

The file mentioned have this line below that expects the option apis.wiki to be defined in my config file, which is not.
```
if (settings.apis.wiki.requireLogin) {
```
 I've tried to defined a `apis.wiki` option in the config file (although I think it should rather check for `allowPublicAccess` option?) and it didn't work either. The error is the following:
```
[2015-06-01T13:19:37.160Z]  INFO: web-sharelatex/18273 on sharelatex: getting page from wiki (page=Main_Page)
[2015-06-01T13:19:37.175Z] ERROR: web-sharelatex/18273 on sharelatex: error passed to top level next middlewear (url=/learn, method=GET)
    Error: Invalid protocol
      at Request.self._buildRequest (/home/sharelatex/sharelatex/web/node_modules/request/request.js:336:53)
      at Request.init (/home/sharelatex/sharelatex/web/node_modules/request/request.js:503:10)
      at new Request (/home/sharelatex/sharelatex/web/node_modules/request/request.js:97:8)
      at request (/home/sharelatex/sharelatex/web/node_modules/request/index.js:50:11)
      at Object.module.exports.WikiController._getPageContent (/home/sharelatex/sharelatex/web/app/js/Features/Wiki/WikiController.js:78:14)
      at /home/sharelatex/sharelatex/web/app/js/Features/Wiki/WikiController.js:41:31
      at Object.module.exports.WikiController._checkIfLoginIsNeeded (/home/sharelatex/sharelatex/web/app/js/Features/Wiki/WikiController.js:23:16)
      at module.exports.WikiController.getPage (/home/sharelatex/sharelatex/web/app/js/Features/Wiki/WikiController.js:27:29)
      at callbacks (/home/sharelatex/sharelatex/web/node_modules/express/lib/router/index.js:161:37)
      at param (/home/sharelatex/sharelatex/web/node_modules/express/lib/router/index.js:135:11)
      at pass (/home/sharelatex/sharelatex/web/node_modules/express/lib/router/index.js:142:5)
      at Router._dispatch (/home/sharelatex/sharelatex/web/node_modules/express/lib/router/index.js:170:5)
      at Object.router (/home/sharelatex/sharelatex/web/node_modules/express/lib/router/index.js:33:10)
      at next (/home/sharelatex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/sharelatex/sharelatex/web/app/js/infrastructure/Server.js:138:14)
      at next (/home/sharelatex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.app.use.res.render.title [as handle] (/home/sharelatex/sharelatex/web/app/js/infrastructure/Server.js:128:12)
...
```
I'm using the master branch (ce10ceb2d941), node 0.10.

**Comment by henryoswald** [comment]
I think this should be fixed, it not drop me an email.
