### ISSUE TITLE
filestore error

### ISSUE THREAD

**Issue by ccgurley** [sharelatex/sharelatex#329]
I'm having some issues getting sharelatex up and running on a rhel6 box, error logs below. 
```
grunt check --force
Running "check:redis" task
Checking Redis is running... OK.
Running Redis version 3.0.2

Running "check:latexmk" task
Checking latexmk is installed... >> FAIL.
>> Unknown latexmk version
Warning: Unknown latexmk version Used --force, continuing.

Running "check:s3" task
Filestore other than S3 configured. Not checking S3.

Running "check:fs" task
Checking FS configuration... OK.

Running "check:aspell" task
Checking aspell is installed... OK.
The following spell check dictionaries are available:

Done, but with warnings.
```
```
grunt run:all
Running "concurrent:all" (concurrent) task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task

Running "execute:web" (execute) task
-> executing /root/sharelatex/web/app.js

Running "execute:document-updater" (execute) task
-> executing /root/sharelatex/document-updater/app.js

Running "execute:real-time" (execute) task
-> executing /root/sharelatex/real-time/app.js

Running "execute:clsi" (execute) task
-> executing /root/sharelatex/clsi/app.js

Running "execute:filestore" (execute) task
-> executing /root/sharelatex/filestore/app.js

Running "execute:docstore" (execute) task
-> executing /root/sharelatex/docstore/app.js

Running "execute:track-changes" (execute) task
-> executing /root/sharelatex/track-changes/app.js

Running "execute:chat" (execute) task
-> executing /root/sharelatex/chat/app.js

Running "execute:tags" (execute) task
-> executing /root/sharelatex/tags/app.js

Running "execute:spelling" (execute) task
-> executing /root/sharelatex/spelling/app.js
[2015-07-01T15:22:25.368Z]  INFO: filestore/7822 on dvm03.csc.ncsu.edu: Loading backend (backend=fs)
info: socket.io started
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Development Enviroment

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
Warning: -> error 8 /root/sharelatex/filestore/app.js (17920ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.
        
        Aborted due to warnings.
```
Any help would be appreciated, Thanks.

**Comment by henryoswald** [comment]
It looks like something is already running on that port. I would highly recommend using the docker version of ShareLaTeX as that is very robust and doesn't have these sort of issues https://github.com/sharelatex/sharelatex-docker-image
