### ISSUE TITLE
CLSI service failing to start due to sqlite in RHEL6

### ISSUE THREAD

**Issue by aniruddhamit** [sharelatex/sharelatex#344]
While trying to start clsi service I am getting error due to which I am able to login to sharelatex but facing problems while creating the project page.

I did try installing sqlite3 package and it installed smoothly. Also I ran the install using npm install sqlite3  and that too worked well but still facing this issue.

P.S. when i am typing sqlite on the terminal it is showing command not found whereas when I am typing sqlite3 on the terminal it is working well. do i have to link both of them ?

---------------------------------------------------- Error -----------------------------------------

/var/www/sharelatex/clsi/node_modules/sequelize/lib/sequelize.js:187
      throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
Error: The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)
    at new module.exports.Sequelize (/var/www/sharelatex/clsi/node_modules/sequelize/lib/sequelize.js:187:13)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/db.js:14:15)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/db.js:48:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/UrlCache.js:4:8)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/UrlCache.js:245:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/ResourceWriter.js:4:14)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/ResourceWriter.js:123:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/CompileManager.js:4:20)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/CompileManager.js:191:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/CompileController.js:6:20)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app/js/CompileController.js:124:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app.js:4:23)
    at Object.<anonymous> (/var/www/sharelatex/clsi/app.js:147:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by dolonnen** [comment]
I have the same problem on Debian Jessie

**Comment by jlazerus** [comment]
In the ShareLaTeX settings file, there is a line underneath the mysql heading for this, can you confirm that it is correct? Here's what mine looks like:
```mysql:
		clsi:
			database: "sharelatex_clsi"
			username: "sharelatex"
			password: "$hareLaTeX"
			dialect: "sqlite"
			storage: Path.join(DATA_DIR, "db.sqlite")

**Comment by henryoswald** [comment]
Hi, we recommend trying the docker release which should solve these sorts
of problems.

On Tue, Dec 1, 2015 at 4:55 PM, Jeff Lazerus <notifications@github.com>
wrote:

> In the ShareLaTeX settings file, there is a line underneath the mysql
> heading for this, can you confirm that it is correct? Here's what mine
> looks like:
>
>         clsi:
>             database: "sharelatex_clsi"
>             username: "sharelatex"
>             password: "$hareLaTeX"
>             dialect: "sqlite"
>             storage: Path.join(DATA_DIR, "db.sqlite")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/344#issuecomment-161030025>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by dolonnen** [comment]
Docker are not available on all machines (e. g. on OpenVZ). But i have "ported" the step your docker file does to a fresh jessie installation and now all works. I think your installation instructions are wrong. Especially the nodejs installation.

**Comment by das7pad** [comment]
Hello,

We've removed the sqlite database a while ago from the clsi service.

Greetings,
Jakob
