### ISSUE TITLE
problem with redis client

### ISSUE THREAD

**Issue by tobiasschweizer** [sharelatex/sharelatex#348]
Hi 

when executing `node web/app.js` I get the following error:

```
{"name":"web-sharelatex","hostname":"myhost","pid":15953,"level":30,"msg":"300 sockets enabled","time":"2015-09-11T14:32:13.072Z","v":0}
Exception: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
  at RedisClient.on_error (/var/www/sharelatex/web/node_modules/redis/index.js:185:24)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/redis/index.js:95:14)
  at Socket.EventEmitter.emit (events.js:95:17)
  at net.js:441:14
  at process._tickDomainCallback (node.js:459:13)

```

I followed the instructions you gave in issue #255 but that did not work for me.

Here is my config file `settings.development.coffee`:

```
Path = require('path')

# These credentials are used for authenticating api requests
# between services that may need to go over public channels
httpAuthUser = "sharelatex"
httpAuthPass = "ca131b8a43dfdcb4bd157c77b44493aa368945e55b6de80d25d5b1e90fb336a463ca4e65598cbc09bc7aa5a4c9a7150c3a8f1b06c1575a300cee572ab317cc02" # Randomly generated for you
httpAuthUsers = {}
httpAuthUsers[httpAuthUser] = httpAuthPass

DATA_DIR = Path.resolve(Path.join(__dirname, "..", "data"))
TMP_DIR = Path.resolve(Path.join(__dirname, "..", "tmp"))

module.exports =
	# Databases
	# ---------

	# ShareLaTeX's main persistant data store is MongoDB (http://www.mongodb.org/)
	# Documentation about the URL connection string format can be found at:
	#
	#    http://docs.mongodb.org/manual/reference/connection-string/
	# 
	# The following works out of the box with Mongo's default settings:
	mongo:
		url : 'mongodb://127.0.0.1/sharelatex'

	# Redis is used in ShareLaTeX for high volume queries, like real-time
	# editing, and session management.
	#
	# The following config will work with Redis's default settings:
	redis:
		web:
			host: "redis"
			port: "6379"
			password: ""
		fairy:
			host: "redis" # my custom host
			port: "6379"
			password: "" # nothing changed here

	# The compile server (the clsi) uses a SQL database to cache files and
	# meta-data. sqllite is the default, and the load is low enough that this will
	# be fine in production (we use sqllite at sharelatex.com).
	#
	# If you want to configure a different database, see the Sequelize documentation
	# for available options:
	#
	#    https://github.com/sequelize/sequelize/wiki/API-Reference-Sequelize#example-usage
	#
	mysql:
		clsi:
			database: "clsi"
			username: "clsi"
			password: ""
			dialect: "sqlite"
			storage: Path.join(DATA_DIR, "db.sqlite")

	# File storage
	# ------------

	# ShareLaTeX can store binary files like images either locally or in Amazon
	# S3. The default is locally:
	filestore:
		backend: "fs"	
		stores:
			user_files: Path.join(DATA_DIR, "user_files")
			
	# To use Amazon S3 as a storage backend, comment out the above config, and
	# uncomment the following, filling in your key, secret, and bucket name:
	#
	#filestore:
	#	backend: "s3"
	#	stores:
	#		user_files: "BUCKET_NAME"
	#	s3:
	#		key: "AWS_KEY"
	#		secret: "AWS_SECRET"
	# 		

	# Local disk caching
	# ------------------
	path:
		# If we ever need to write something to disk (e.g. incoming requests
		# that need processing but may be too big for memory), then write
		# them to disk here:
		dumpFolder:   Path.join(TMP_DIR, "dumpFolder")
		# Where to write uploads before they are processed
		uploadFolder: Path.join(TMP_DIR, "uploads")
		# Where to write the project to disk before running LaTeX on it
		compilesDir:  Path.join(DATA_DIR, "compiles")
		# Where to cache downloaded URLs for the CLSI
		clsiCacheDir: Path.join(DATA_DIR, "cache")

	# Server Config
	# -------------

	# Where your instance of ShareLaTeX can be found publicly. This is used
	# when emails are sent out and in generated links:
	siteUrl : 'http://localhost:3000'
	
	# The websocket layer of ShareLaTeX runs as separate service.
	# When running locally or in development, you can point the client to this
	# service directly on port 3026. If you are running behind a reverse proxy (Nginx, etc)
	# then websocketsUrl should be the same as siteUrl, with your reverse
	# proxy responible for sending websocket traffic to the websocket service
	# rather than connecting directly.
	websocketsUrl: 'http://localhost:3026'
	
	# If provided, a sessionSecret is used to sign cookies so that they cannot be
	# spoofed. This is recommended.
	security:
		sessionSecret: "8c0162b8c626ac6ac8ce75bd536c9addc3d9685148c61d1f169601e67664a136272695fb828794cbd707ab3f32d8471a418407f28d9f4ddaa5f31f4744ca2f85" # This was randomly generated for you

	# These credentials are used for authenticating api requests
	# between services that may need to go over public channels
	httpAuthUsers: httpAuthUsers
	
	# Should javascript assets be served minified or not. Note that you will
	# need to run `grunt compile:minify` within the web-sharelatex directory
	# to generate these.
	useMinifiedJs: false

	# Should static assets be sent with a header to tell the browser to cache
	# them. This should be false in development where changes are being made,
	# but should be set to true in production.
	cacheStaticAssets: false

	# If you are running ShareLaTeX over https, set this to true to send the
	# cookie with a secure flag (recommended).
	secureCookie: false
	
	# If you are running ShareLaTeX behind a proxy (like Apache, Nginx, etc)
	# then set this to true to allow it to correctly detect the forwarded IP
	# address and http/https protocol information.
	behindProxy: false

	# Sending Email
	# -------------
	#
	# You must configure a mail server to be able to send invite emails from
	# ShareLaTeX. The config settings are passed to nodemailer. See the nodemailer
	# documentation for available options:
	#
	#     http://www.nodemailer.com/docs/transports
	#
	# email:
	#	fromAddress: ""
	#	replyTo: ""
	#	transport: "SES"
	#	parameters:
	#		AWSAccessKeyID: ""
	#		AWSSecretKey: ""

	# Spell Check Languages
	# ---------------------
	#
	# You must have the corresponding aspell dictionary installed to 
	# be able to use a language. Run `grunt check:aspell` to check which
	# dictionaries you have installed. These should be set for the `code` for
	# each language.
	languages: [
		{name: "English", code: "en"}
	]
	
	# Service locations
	# -----------------

	# ShareLaTeX is comprised of many small services, which each expose
	# an HTTP API running on a different port. Generally you
	# can leave these as they are unless you have some other services
	# running which conflict, or want to run the web process on port 80.
	#internal:
	#	web:
	#		port: webPort = 3000
	#		host: "localhost"
	#	documentupdater:
	#		port: docUpdaterPort = 3003
	#		host: "localhost"
	#	filestore:
	#		port: filestorePort = 3009
	#		host: "localhost"
	#	chat:
	#		port: chatPort = 3010
	#		host: "localhost"
	#	tags:
	#		port: tagsPort = 3012
	#		host: "localhost"
	#	clsi:
	#		port: clsiPort = 3013
	#		host: "localhost"
	#	trackchanges:
	#		port: trackchangesPort = 3015
	#		host: "localhost"
	#	docstore:
	#		port: docstorePort = 3016
	#		host: "localhost"
	#	spelling:
	# 		port: spellingPort = 3005
	#		host: "localhost"
	#	realTime:
	#		port: realTimeport = 3026
	#		host: "localhost"

	# If you change the above config, or run some services on remote servers,
	# you need to tell the other services where to find them:
	apis:
		web:
			url: "http://localhost:3000"
			user: httpAuthUser
			pass: httpAuthPass
	#	documentupdater:
	#		url : "http://localhost:#{docUpdaterPort}"
	#	clsi:
	#		url: "http://localhost:#{clsiPort}"
	#	filestore:
	#		url: "http://localhost:#{filestorePort}"
	#	trackchanges:
	#		url: "http://localhost:#{trackchangesPort}"
	#	docstore:
	#		url: "http://localhost:#{docstorePort}"
	#	tags:
	#		url: "http://localhost:#{tagsPort}"
	#	spelling:
	#		url: "http://localhost:#{spellingPort}"
	#	chat:
	#		url: "http://localhost:#{chatPort}"
	

# With lots of incoming and outgoing HTTP connections to different services,
# sometimes long running, it is a good idea to increase the default number
# of sockets that Node will hold open.
http = require('http')
http.globalAgent.maxSockets = 300
https = require('https')
https.globalAgent.maxSockets = 300
```  

When I run `grunt run:all` I get:

```
Running "execute:clsi" (execute) task
-> executing /var/www/sharelatex/clsi/app.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Development Enviroment

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
Warning: -> error 8 /var/www/sharelatex/filestore/app.js (917ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.
        
        Aborted due to warnings.

```

Would be great if you could give me some advice!

**Comment by henryoswald** [comment]
It looks like you have a combination of old node processes running so kill all them (killall node) and redis isn't running on 127.0.0.1:6379 if you do redis-cli it should connect. I recommend using the docker image https://github.com/sharelatex/sharelatex-docker-image to get setup.

**Comment by tobiasschweizer** [comment]
Hi 

Thanks for your answer. It was my fault: I did not install redis in the first place. On Linux, I had to run `sudo apt-get install redis-server redis-tools`.

Now I can call `localhost:3000`

Now there is another problem: the websocket does not seem to be available:

![websocket](https://cloud.githubusercontent.com/assets/6000023/9986966/b7d0fbc4-6042-11e5-888d-a1585a3f5e66.png)

Running `node web/app.js` says:

```
{"name":"web-sharelatex","hostname":"myhost","pid":3274,"level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n  at errnoException (net.js:901:11)\n  at Object.afterConnect [as oncomplete] (net.js:892:19)\n","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"url":"/socket.io/socket.io.js","method":"GET","msg":"error passed to top level next middlewear","time":"2015-09-21T07:26:22.565Z","v":0}
```

Do I miss another service?  How could I test this service separately?

**Comment by tobiasschweizer** [comment]
in my config file, the websocketsURl is defined:

```
# The websocket layer of ShareLaTeX runs as separate service.
        # When running locally or in development, you can point the client to this
        # service directly on port 3026. If you are running behind a reverse proxy (Nginx, etc)
        # then websocketsUrl should be the same as siteUrl, with your reverse
        # proxy responible for sending websocket traffic to the websocket service
        # rather than connecting directly.
        websocketsUrl: 'http://localhost:3026'

```

But under http://localhost:3026 there is not service available. How do I set this service up?

**Comment by henryoswald** [comment]
Hey its really hard to debug these issues remotely sorry which is why we created the docker image at https://github.com/sharelatex/sharelatex-docker-image can you try that?

**Comment by tobiasschweizer** [comment]
Ok, I understand. I will try to run the docker image.

The reason why I wanted to install sharelatex on my machine directly is because I would like to know how this exactly works.

**Comment by jofftiquez** [comment]
@tobiasschweizer I had the same problem LOL. Installing redis will be the perfect solution.
