### ISSUE TITLE
nodemailer configuration

### ISSUE THREAD

**Issue by Xarin** [sharelatex/sharelatex#390]
I can't seem to get email working for sharelatex (docker container). Every configuration I try actually breaks sharelatex entirely causing it to throw nginx errors unless I leave the entire email section commented out.
below I used the configuration listed [here](https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email) although I have tried several others as well. [(other configs)](http://blog.nodeknockout.com/post/34641712180/sending-email-from-nodejs) any help would be appreciated.
Thanks!

# Settings.coffee
        # Sending Email
        # -------------
        #
        # You must configure a mail server to be able to send invite emails from
        # ShareLaTeX. The config settings are passed to nodemailer. See the nodemailer
        # documentation for available options:
        #
        #     http://www.nodemailer.com/docs/transports (no longer exists)
        # (line 140)
         email:
               fromAddress: "name@email"
               replyTo: "name@email"
        #       service "Gmail",
               transport: "SMTP"
               parameters:
                       host: "smtp.server.edu"
                       port: "25"
                       authMethod: "PLAIN"
                       auth: {
                               user: 'name@email',
                               pass: 'password'
                       }
                       secure: false

        # Spell Check Languages

# Error
/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:82
      throw err;
            ^
Error: In /etc/sharelatex/settings.coffee, Parse error on line 140: Unexpected '{'
  at Object.parseError (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/parser.js:483:11)
  at Object.parse (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/parser.js:535:22)
  at exports.compile.compile (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:60:27)
  at Object.loadFile (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:28)
  at Module.load (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/Settings.coffee:32:26)
  at Object.<anonymous> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/Settings.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
  at Module.load (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/index.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/sharelatex/real-time/app.js:16:14)
  at Object.<anonymous> (/var/www/sharelatex/real-time/app.js:89:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3

**Comment by henryoswald** [comment]
check your tabs are not spaces, the config can not be read for some reason.

On Mon, Feb 8, 2016 at 3:23 PM, Xarin <notifications@github.com> wrote:

> I can't seem to get email working for sharelatex (docker container) Every
> configuration I try actually breaks sharelatex entirely causing it to throw
> nginx errors unless I leave the entire email section commented out
> below I used the configuration listed here
> <https://githubcom/sharelatex/sharelatex/wiki/Configuring-SMTP-Email>
> although I have tried several others as well (other configs)
> <http://blognodeknockoutcom/post/34641712180/sending-email-from-nodejs>
> any help would be appreciated
> Thanks!
> Settingscoffee
>
>     # Sending Email
>     # -------------
>     #
>     # You must configure a mail server to be able to send invite emails from
>     # ShareLaTeX The config settings are passed to nodemailer See the nodemailer
>     # documentation for available options:
>     #
>     #     http://wwwnodemailercom/docs/transports (no longer exists)
>     # (line 140)
>      email:
>            fromAddress: "name@email"
>            replyTo: "name@email"
>     #       service "Gmail",
>            transport: "SMTP"
>            parameters:
>                    host: "smtpserveredu"
>                    port: "25"
>                    authMethod: "PLAIN"
>                    auth: {
>                            user: 'name@email',
>                            pass: 'password'
>                    }
>                    secure: false
>
>     # Spell Check Languages
>
> Error
>
>
> /var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-scriptjs:82
> throw err;
> ^
> Error: In /etc/sharelatex/settingscoffee, Parse error on line 140:
> Unexpected '{'
> at ObjectparseError
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/parserjs:483:11)
> at Objectparse
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/parserjs:535:22)
> at exportscompilecompile
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-scriptjs:60:27)
> at ObjectloadFile
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-scriptjs:24:28)
> at Moduleload
> (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/coffee-script/lib/coffee-script/registerjs:45:36)
> at FunctionModule_load (modulejs:312:12)
> at Modulerequire (modulejs:364:17)
> at require (modulejs:380:17)
> at Object
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/Settingscoffee:32:26)
> at Object
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/Settingscoffee:1:1)
> at Module_compile (modulejs:456:26)
> at ObjectloadFile
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-scriptjs:24:19)
> at Moduleload
> (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/coffee-script/lib/coffee-script/registerjs:45:36)
> at FunctionModule_load (modulejs:312:12)
> at Modulerequire (modulejs:364:17)
> at require (modulejs:380:17)
> at Object
> (/var/www/sharelatex/real-time/node_modules/settings-sharelatex/indexjs:2:18)
> at Module_compile (modulejs:456:26)
> at ObjectModule_extensionsjs (modulejs:474:10)
> at Moduleload
> (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/coffee-script/lib/coffee-script/registerjs:45:36)
> at FunctionModule_load (modulejs:312:12)
> at Modulerequire (modulejs:364:17)
> at require (modulejs:380:17)
> at Object (/var/www/sharelatex/real-time/appjs:16:14)
> at Object (/var/www/sharelatex/real-time/appjs:89:4)
> at Module_compile (modulejs:456:26)
> at ObjectModule_extensionsjs (modulejs:474:10)
> at Moduleload (modulejs:356:32)
> at FunctionModule_load (modulejs:312:12)
> at FunctionModulerunMain (modulejs:497:10)
> at startup (nodejs:119:16)
> at nodejs:935:3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/390>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by Xarin** [comment]
Thanks! email: had an extra space so now its at least starting.
