### ISSUE TITLE
Cannot start docker container on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by turbo0628** [sharelatex/sharelatex#474]
I'm following the deployment instructions with docker and cannot start ShareLatex properly. My system is ubuntu 16.04.1 with docker 1.12.1, mongodb 3.2.9 and redis 3.2.3

I'm using command 
docker run -d -v ~/sharelatex_data:/var/lib/sharelatex -p 5000:80 --name=sharelatex sharelatex/sharelatex

But it's not running anyway. 
The docker logs output is

~~~
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/99_migrate.sh...
/usr/bin/node
/usr/bin/grunt
total 40
drwxr-xr-x  2 root root  4096 Jun 30 14:13 .
drwxr-xr-x 21 root root  4096 Jun 30 14:26 ..
-rw-r--r--  1 root root  5074 Jun 30 14:13 1_move_doc_lines_to_doc_collection.coffee
-rw-r--r--  1 root root  5936 Jun 30 14:13 2_doc_lines_delete_from_project.coffee
-rw-r--r--  1 root root 10606 Jun 30 14:13 3_pack_docHistory_collection.coffee
-rw-r--r--  1 root root   179 Jun 30 14:13 about_migrations.md
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bunyan" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Loading "bunyan.js" tasks...OK
+ bunyan

Registering "grunt-execute" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Loading "execute.js" tasks...OK
+ execute

Registering "grunt-available-tasks" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Loading "available_tasks.js" tasks...OK
+ availabletasks

Registering "grunt-concurrent" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-shell" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ build:upstart_scripts, check, check:aspell, check:fs, check:latexmk, check:make, check:redis, check:s3, default, help, install, install:all, install:chat, install:clsi, install:dirs, install:docstore, install:document-updater, install:filestore, install:real-time, install:spelling, install:tags, install:track-changes, install:web, migrate, release:chat, release:clsi, release:docstore, release:document-updater, release:filestore, release:real-time, release:spelling, release:tags, release:track-changes, release:web, run, run:all, run:chat, run:clsi, run:docstore, run:document-updater, run:filestore, run:real-time, run:spelling, run:tags, run:track-changes, run:web, update, update:all, update:chat, update:clsi, update:docstore, update:document-updater, update:filestore, update:real-time, update:spelling, update:tags, update:track-changes, update:web

Running tasks: migrate

Running "migrate" task

Running "coffee:migrate" (coffee) task
Verifying property coffee.migrate exists in config...OK
Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
Reading migrations/2_doc_lines_delete_from_project.coffee...OK
Writing migrations/2_doc_lines_delete_from_project.js...OK
Reading migrations/3_pack_docHistory_collection.coffee...OK
Writing migrations/3_pack_docHistory_collection.js...OK

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex

/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
	this.db.close(callback);
	        ^
TypeError: Cannot call method 'close' of undefined
    at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:10)
    at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
    at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
    at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:148:20)
    at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
    at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:155:17)
    at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
    at /var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:69:17
Warning: Command failed: 
/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
	this.db.close(callback);
	        ^
TypeError: Cannot call method 'close' of undefined
    at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:10)
    at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
    at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
    at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:148:20)
    at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
    at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:155:17)
    at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
    at /var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:69:17
 Use --force to continue.

Aborted due to warnings.
*** /etc/my_init.d/99_migrate.sh failed with status 6

*** Killing all processes...


~~~

Thanks in advance.

**Comment by henryoswald** [comment]
it can't talk to your mongodb instance.
