### ISSUE TITLE
latest docker image: STMP issues with SSL and startTLS

### ISSUE THREAD

**Issue by bonanza123** [sharelatex/sharelatex#477]
I'm trying to setup STMP with the latest sharelatex docker image using the docker-compose file in this repo.

I tried it with the minimal setup (where I hoped that sharelatex or nodemailer would simply pick the correct defaults) and also with many other combinations of the SECURE and TLS related environment variables.

```
SHARELATEX_EMAIL_FROM_ADDRESS: "root@sharelatex.domain.tld"
SHARELATEX_EMAIL_SMTP_HOST: "smtp.domain.tld"
SHARELATEX_EMAIL_SMTP_PORT: 587
SHARELATEX_EMAIL_SMTP_USER: "user@stmp.domain.tld"
SHARELATEX_EMAIL_SMTP_PASS: "mysuperpassword"
```

which fails with:

```
{"name":"web-sharelatex","hostname":"6945c902c2ef","pid":77,"level":30,"receiver":"user@domain.tld","subject":"Password Reset - Our ShareLaTeX","msg":"sending email","time":
"2016-10-06T15:14:46.603Z","v":0}
{"name":"web-sharelatex","hostname":"6945c902c2ef","pid":77,"level":50,"err":{"message":"Mail command failed: 451 Requested action aborted: local error in processing","name":"Error","stack"
:"Error: Mail command failed: 451 Requested action aborted: local error in processing\n  at SMTPConnection._formatError (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemai
ler-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:424:15)\n  at SMTPConnection._actionMAIL (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp
-transport/node_modules/smtp-connection/lib/smtp-connection.js:935:30)\n  at SMTPConnection.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transpo
rt/node_modules/smtp-connection/lib/smtp-connection.js:625:14)\n  at SMTPConnection._processResponse (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/
node_modules/smtp-connection/lib/smtp-connection.js:559:16)\n  at SMTPConnection._onData (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules
/smtp-connection/lib/smtp-connection.js:389:10)\n  at CleartextStream.emit (events.js:95:17)\n  at CleartextStream.<anonymous> (_stream_readable.js:765:14)\n  at CleartextStream.emit (event
s.js:92:17)\n  at emitReadable_ (_stream_readable.js:427:10)\n  at _stream_readable.js:420:7\n  at process._tickDomainCallback (node.js:502:13)\n","code":"EENVELOPE"},"msg":"error sending m
essage","time":"2016-10-06T15:14:49.861Z","v":0}
```

**Comment by cnwangfeng** [comment]
@bonanza123 , I got the same probllem. Have you resolved the problem?

**Comment by aquac** [comment]
@cnwangfeng I am currently using these settings:

```
SHARELATEX_EMAIL_SMTP_HOST: "smtp.1und1.de"
SHARELATEX_EMAIL_SMTP_PORT: 465
SHARELATEX_EMAIL_SMTP_SECURE: 'true'
SHARELATEX_EMAIL_SMTP_USER: "user@vla.com"
SHARELATEX_EMAIL_SMTP_PASS: "myPW"
SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: 'false'
SHARELATEX_EMAIL_SMTP_IGNORE_TLS: 'true'
```

this works for me, but in general I have the feeling that SMTP is still very buggy with overleaf, best of luck!
