### ISSUE TITLE
Error starting sharelatex/sharelatex docker container

### ISSUE THREAD

**Issue by onlymrdp** [sharelatex/sharelatex#484]
**EDIT: I just recognized I was totally my mistake that sharelatex wasn't even reachable. This was due to a https://[my_domain]:5123 I forgot to delete. It IS reachable now. But I won`t delete this issue due to the fact that this error warnings might help you fixing something. If you don't think so, please delete/close this**

I just tried to install a new instance of Sharelatex on my Linux server (Debian 8). For this I used docker like recommended.

My run command locks like this:

```
docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5123:80 \
  --name=sharelatex \
  --env SHARELATEX_SITE_URL=[domain_censored_for_privacy_reasons]:5123 \
  --env SHARELATEX_ADMIN_EMAIL=[email_censored_for_privacy_reasons] \
  sharelatex/sharelatex
```

Due to the fact that the server doesn't accept connections after starting sharelatex, I tried "docker logs sharelatex" and this was the output:

```
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'check:redis'

Running "check:redis" task
Checking can connect to redis
node_redis: Warning: Redis server does not require a password, but a password wa                                                                s supplied.
OK.
Done, without errors.
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'check:mongo'

Running "check:mongo" task
Checking can connect to mongoOK.
Done, without errors.
All checks passed
*** Running /etc/my_init.d/99_migrate.sh...
/usr/bin/node
/usr/bin/grunt
total 40
drwxr-xr-x  2 root root  4096 Oct 19 11:33 .
drwxr-xr-x 22 root root  4096 Oct 19 11:47 ..
-rw-r--r--  1 root root  5074 Oct 19 11:33 1_move_doc_lines_to_doc_collection.co                                                                ffee
-rw-r--r--  1 root root  5936 Oct 19 11:33 2_doc_lines_delete_from_project.coffe                                                                e
-rw-r--r--  1 root root 10606 Oct 19 11:33 3_pack_docHistory_collection.coffee
-rw-r--r--  1 root root   179 Oct 19 11:33 about_migrations.md
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bunyan" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Loading "bunyan.js" tasks...OK
+ bunyan

Registering "grunt-execute" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Loading "execute.js" tasks...OK
+ execute

Registering "grunt-available-tasks" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Loading "available_tasks.js" tasks...OK
+ availabletasks

Registering "grunt-concurrent" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-shell" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell
Initializing config...OK
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'migrate'
>>   at Object.fs.lstatSync (fs.js:691:18)
>>   at Object.<anonymous> (/var/www/sharelatex/grunt/ProjectSize.coffee:10:15)
>>   at Object.<anonymous> (/var/www/sharelatex/grunt/ProjectSize.coffee:1:1)
>>   at Module._compile (module.js:456:26)
>>   at Object.loadFile (/var/www/sharelatex/node_modules/settings-sharelatex/no                                                                de_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Module.require (module.js:364:17)
>>   at require (module.js:380:17)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/r                                                                eadfile.js:28:16)
>>   at /var/www/sharelatex/node_modules/load-grunt-config/lib/readconfigdir.js:                                                                21:18
>>   at Array.forEach (native)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/r                                                                eadconfigdir.js:19:9)
>>   at /var/www/sharelatex/node_modules/load-grunt-config/lib/gruntconfig.js:10                                                                :28
>>   at arrayReduce (/var/www/sharelatex/node_modules/lodash/index.js:1450:23)
>>   at Function.<anonymous> (/var/www/sharelatex/node_modules/lodash/index.js:3                                                                445:13)
>>   at LodashWrapper.reduce (/var/www/sharelatex/node_modules/lodash/index.js:1                                                                1369:27)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/g                                                                runtconfig.js:9:6)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/index                                                                .js:33:16)
>>   at Object.module.exports (/var/www/sharelatex/Gruntfile.coffee:245:2)
>>   at loadTask (/var/www/sharelatex/node_modules/grunt/lib/grunt/task.js:325:1                                                                0)
>>   at Task.task.init (/var/www/sharelatex/node_modules/grunt/lib/grunt/task.js                                                                :437:5)
>>   at Object.grunt.tasks (/var/www/sharelatex/node_modules/grunt/lib/grunt.js:                                                                120:8)
>>   at Object.module.exports [as cli] (/var/www/sharelatex/node_modules/grunt/l                                                                ib/grunt/cli.js:38:9)
>>   at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:456:26)
>>   at Object.Module._extensions..js (module.js:474:10)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Function.Module.runMain (module.js:497:10)
>>   at startup (node.js:119:16)
>>   at node.js:945:3

Running tasks: migrate

Running "migrate" task

Running "coffee:migrate" (coffee) task
Verifying property coffee.migrate exists in config...OK
Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move                                                                _doc_lines_to_doc_collection.js
Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lin                                                                es_delete_from_project.js
Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHi                                                                story_collection.js
Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n                                                                "
Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
Reading migrations/2_doc_lines_delete_from_project.coffee...OK
Writing migrations/2_doc_lines_delete_from_project.js...OK
Reading migrations/3_pack_docHistory_collection.coffee...OK
Writing migrations/3_pack_docHistory_collection.js...OK

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=fal                                                                se, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb                                                                ://dockerhost/sharelatex
nothing to migrate

Done, without errors.
All migrations finished
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 77
Nov  1 21:49:14 42fdccffe3e5 syslog-ng[106]: syslog-ng starting up; version='3.5                                                                .3'
```

My interpretation of it is, that connections to MongoDb and Redis seem to be fine. The problem seems to be within the Gruntfile.coffee files.

I should mention that I had a running sharelatex installation some time ago on the same server, but for some reasons (not linked to sharelatex) I stopped it and deleted the image by using "docker rmi sharelatex/sharelatex". Also I deleted the sharelatex_data folder some time after that. By this I think there shouldn't be any problems due to old installations. 

(Oh and I even wipped MongoDb and Redis -  one of the reasons I decided to "uninstall" sharelatex back then)

**Comment by henryoswald** [comment]
Hi,

which version of the container are you running?

**Comment by onlymrdp** [comment]
I;m using the image with the tag "latest" and Image ID "dbb209a28710" which was created 2 weeks ago (Just because I didn't know better)

**Comment by onlymrdp** [comment]
Short information: I pulled v0.3.10 today, to test if there aren't those problems. And everything is fine with that. It may be a good solution to put this version into the Wiki article of "Quick Start Guide", just to remind guys like me not to use the latest version.

**Comment by henryoswald** [comment]
dbb209a28710 doesn't look like one of our versions, is that the container id?

**Comment by onlymrdp** [comment]
Yes it is:

REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
sharelatex/sharelatex   latest              dbb209a28710        4 weeks ago  

I received that image be simply running:

`docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5123:80 \
  --name=sharelatex \
  --env SHARELATEX_SITE_URL=[domain_censored_for_privacy_reasons]:5123 \
  --env SHARELATEX_ADMIN_EMAIL=[email_censored_for_privacy_reasons] \
  sharelatex/sharelatex`

I am not a docker expert i must admit, but I think "sharelatex/sharelatex" should lead to one of your versions.

**Comment by onlymrdp** [comment]
Today I pulled some other versions out of your repository and found out thát the version with image ID "dbb209a28710" seems to be v0.4.2 (output of "docker images sharelatex/sharelatex"):

| REPOSITORY            |  TAG            |     IMAGE ID       |     CREATED    |        SIZE |
| ---------| -----------| -------------| ----------| -----------|
| sharelatex/sharelatex   | latest       |       dbb209a28710      |  4 weeks ago  | 2.361 GB |
| sharelatex/sharelatex   | v0.4.2      |       dbb209a28710      |  4 weeks ago  | 2.361 GB |
| sharelatex/sharelatex   |  v0.3.10    |        8c69309bc22e      |  4 months ago   |     2.285 GB |

As I saw in the release notes of 0.4.0 here on github it is not yet to be released, so that may be the problem.

This was something I didn't realize two days ago, cause I checked the available versions through

```
wget -q https://registry.hub.docker.com/v1/repositories/sharelatex/sharelatex/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'
```

instead of taking a look at the actual website (https://hub.docker.com/r/sharelatex/sharelatex/tags/)
