### ISSUE TITLE
502 Bad Gateway on docker fresh install

### ISSUE THREAD

**Issue by julianmaster** [sharelatex/sharelatex#487]
Hi,

I follow your "Quick Start Guide" but after 3 hours of bug I don't find solution for the 502 Bad Gateway Error.

I run the command :
```
docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --name=sharelatex \
  sharelatex/sharelatex
```
My server is a Debian Jessie. And I have a Apache working well.

There is other think to do for working ?
Any help ?

Thank

**Comment by garmante** [comment]
I second this. I followed the Quick Start and got web error 502. I also had errors trying to add an admin account with the grunt command to add an admin.

Thanks.

**Comment by AnzoChou** [comment]
+1

**Comment by henryoswald** [comment]
anything in your logs?

**Comment by AnzoChou** [comment]
Using the compose file fixed the issue for me.
1.install the [docker-compose](https://github.com/docker/compose/releases)
2.use the script below:
```bash
mkdir sharelatex && cd ./sharelatex
wget https://github.com/sharelatex/sharelatex/blob/master/docker-compose.yml
docker-compose up
```
3.open `http://<server_ip>/` (default port is **80**)

**Comment by mimischi** [comment]
Same problem with the current Dockerfile. Using docker-compose and setting up nginx with a proxy to the container port works flawlessly!

**Comment by julianmaster** [comment]
AnzoChou, I follow your instruction but I have an error :
```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 7, column 19
```
A solution ?

**Comment by julianmaster** [comment]
Okay a find the solution.
I give the full script for the install :

1.install docker
2.install sharelatex with redis and mongodb  
```
curl -L "https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
mkdir sharelatex && cd ./sharelatex
wget https://raw.githubusercontent.com/sharelatex/sharelatex/master/docker-compose.yml
docker-compose up -d
```  
3.Enjoy !  

Errors :
* Error 1 :
	```
	ERROR: for sharelatex  Cannot create container for service sharelatex: Conflict. The name "/sharelatex" is already in use by container f2fc30b5e0313b6c90f052afa89c774e461540f57fb8cf12785e83c130940571. You have to remove (or rename) that container to be able to reuse that name.
	ERROR: Encountered errors while bringing up the project.
	```

	Solution : You have a previous install of sharelatex. And you need to remove the container with command `docker stop sharelatex && docker rm sharelatex`
* Error 2 :
	```
	ERROR: for sharelatex  Cannot start service sharelatex: driver failed programming
	in use
	ERROR: Encountered errors while bringing up the project.
	```

	Solution : You have a service that running on port 80. You need to change in the script `docker-compose.yml`, before run the `docker-compose up -d`, the line `- 80:80` (line 12)

**Comment by shoeper** [comment]
Both methods didn't work here. I've tried multiple times on a fresh install. This is the log from `docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex   -p 5000:80   --name=sharelatex   sharelatex/sharelatex`

```
Checking can connect to mongo and redis
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'check:redis'

Running "check:redis" task
Checking can connect to redis
>> FAIL.
>> !!!!!!!!!!!!!! REDIS ERROR !!!!!!!!!!!!!!
>> 
>> ShareLaTeX can not talk to the redis instance
>> 
>> Check the redis instance is running and accessible on env var
>> SHARELATEX_REDIS_URL
>> 
>> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal error: Can not connect to redis
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'check:mongo'

Running "check:mongo" task
Checking can connect to mongo>> FAIL.
>> !!!!!!!!!!!!!! MONGO ERROR !!!!!!!!!!!!!!
>> 
>> ShareLaTeX can not talk to the mongdb instance
>> 
>> Check the mongodb instance is running and accessible on env var
>> SHARELATEX_MONGO_URL
>> 
>> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal error: Can not connect to Mongodb
All checks passed
/usr/bin/node
/usr/bin/grunt
total 51
drwxr-xr-x  2 root root     6 Oct 19 11:33 .
drwxr-xr-x 19 root root    27 Oct 19 11:47 ..
-rw-r--r--  1 root root  5074 Oct 19 11:33 1_move_doc_lines_to_doc_collection.coffee
-rw-r--r--  1 root root  5936 Oct 19 11:33 2_doc_lines_delete_from_project.coffee
-rw-r--r--  1 root root 10606 Oct 19 11:33 3_pack_docHistory_collection.coffee
-rw-r--r--  1 root root   179 Oct 19 11:33 about_migrations.md
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bunyan" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Loading "bunyan.js" tasks...OK
+ bunyan

Registering "grunt-execute" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Loading "execute.js" tasks...OK
+ execute

Registering "grunt-available-tasks" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Loading "available_tasks.js" tasks...OK
+ availabletasks

Registering "grunt-concurrent" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-shell" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell
Initializing config...OK
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'migrate'
>>   at Object.fs.lstatSync (fs.js:691:18)
>>   at Object.<anonymous> (/var/www/sharelatex/grunt/ProjectSize.coffee:10:15)
>>   at Object.<anonymous> (/var/www/sharelatex/grunt/ProjectSize.coffee:1:1)
>>   at Module._compile (module.js:456:26)
>>   at Object.loadFile (/var/www/sharelatex/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Module.require (module.js:364:17)
>>   at require (module.js:380:17)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/readfile.js:28:16)
>>   at /var/www/sharelatex/node_modules/load-grunt-config/lib/readconfigdir.js:21:18
>>   at Array.forEach (native)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/readconfigdir.js:19:9)
>>   at /var/www/sharelatex/node_modules/load-grunt-config/lib/gruntconfig.js:10:28
>>   at arrayReduce (/var/www/sharelatex/node_modules/lodash/index.js:1450:23)
>>   at Function.<anonymous> (/var/www/sharelatex/node_modules/lodash/index.js:3445:13)
>>   at LodashWrapper.reduce (/var/www/sharelatex/node_modules/lodash/index.js:11369:27)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/gruntconfig.js:9:6)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/index.js:33:16)
>>   at Object.module.exports (/var/www/sharelatex/Gruntfile.coffee:245:2)
>>   at loadTask (/var/www/sharelatex/node_modules/grunt/lib/grunt/task.js:325:10)
>>   at Task.task.init (/var/www/sharelatex/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (/var/www/sharelatex/node_modules/grunt/lib/grunt.js:120:8)
>>   at Object.module.exports [as cli] (/var/www/sharelatex/node_modules/grunt/lib/grunt/cli.js:38:9)
>>   at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:456:26)
>>   at Object.Module._extensions..js (module.js:474:10)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Function.Module.runMain (module.js:497:10)
>>   at startup (node.js:119:16)
>>   at node.js:945:3

Running tasks: migrate

Running "migrate" task

Running "coffee:migrate" (coffee) task
Verifying property coffee.migrate exists in config...OK
Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
Reading migrations/2_doc_lines_delete_from_project.coffee...OK
Writing migrations/2_doc_lines_delete_from_project.js...OK
Reading migrations/3_pack_docHistory_collection.coffee...OK
Writing migrations/3_pack_docHistory_collection.js...OK

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex
Warning: Command failed: 
/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
	this.db.close(callback);
	        ^
TypeError: Cannot call method 'close' of undefined
    at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:10)
    at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
    at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
    at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:148:20)
    at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
    at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:155:17)
    at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
    at /var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:69:17
 Use --force to continue.

Aborted due to warnings.
All migrations finished
Nov 11 21:10:55 aa7967fa9cef syslog-ng[104]: syslog-ng starting up; version='3.5.3'
```

**Comment by julianmaster** [comment]
shoeper do you follow the step I give ?

**Comment by shoeper** [comment]
Yes, I also tried

```
curl -L "https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
mkdir sharelatex && cd ./sharelatex
wget https://raw.githubusercontent.com/sharelatex/sharelatex/master/docker-compose.yml
docker-compose up -d
```
Didn't work either. Unfortunately don't have the logs anymore.

**Comment by julianmaster** [comment]
Do you each time use a fresh install with a empty docker ? Because the code don't working if a previous sharelatex is created

**Comment by shoeper** [comment]
yes

**Comment by AnzoChou** [comment]
@shoeper , please try the install script below. I have tested it under various conditions. (ubuntu 14.04 LTS)
1. create a file **install.sh**.
2. copy and paste the script below into it.
3. run `sudo bash install.sh`

```bash
#!/bin/bash
echo "Step 1. install docker-compose"
curl -L "https://github.com/docker/compose/releases/download/1.9.0-rc4/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
echo ""
echo "Step 2. download the compose file for sharelatex"
mkdir sharelatex && cd ./sharelatex && rm docker-compose.yml
wget https://raw.githubusercontent.com/sharelatex/sharelatex/master/docker-compose.yml
echo ""
echo "Step 3. change default web port to 5000 to avoid conflicts (optional)"
sed -i -e "s/ - 80:80/ - 5000:80/g" ./docker-compose.yml
echo ""
echo "Step 4. remove old containers and images"
docker rm -f sharelatex
docker rm -f mongo
docker rm -f redis
# please comment three lines below if you don't want to download the images again
docker rmi sharelatex/sharelatex
docker rmi mongo
docker rmi redis
echo ""
echo "Step 4. download dependencies and run the server."
echo "Please open http://<server_ip>:5000 and check whether it works."
echo "If you run into any problems, please see the logs below for details. press <CTRL+C> to stop the server"
echo ""
docker-compose up
echo ""
echo "If it works well, you can run the server in the background next time by 'docker-compose up -d'."
echo "Enjoy!"
```

**Comment by shoeper** [comment]
I don't see any difference to what I've done yesterday. Maybe I'll try it later. Takes some time because my connection isn't that fast (server is located at home).

**Comment by shoeper** [comment]
Ok on a fresh debian jessie install it works.

**Comment by garmante** [comment]
@AnzoChou, thanks for the script. worked really well. I have one question, though. How (or in what container) do I add the admin user? Thanks

**Comment by benoitldr** [comment]
Hi,
I reinstall sharelatex again and with this solution it's works directly

**Comment by tfabbri** [comment]
I am experiencing a 502 Bad Gateway error using the docker-compose file. 

The only solution that works in my case is the one provided by @MiauWuffMiau in the issue titled   [502 Error ](https://github.com/sharelatex/sharelatex-docker-image/issues/2#issuecomment-210445939) from the sharelatex-docker-image repo. I am installing it on my VPS, Ubuntu 16.04
