### ISSUE TITLE
Sharelatex doesn't open old tex files after migration

### ISSUE THREAD

**Issue by giovannesant** [sharelatex/sharelatex#528]
Hi,

after migrate sharelatex running in a machine to another machine and restore data from backup, just old tex files doesn't open. They keep loading infinite. 

* If I create a new project, its works correctly.
* db.projects.find().pretty() list all projects correctly.

- Official Docker version being run:
Docker version 17.04.0-ce, build 4845c56

- Errors that appears in web.log:

``` 
{"name":"web-sharelatex","hostname":"8db5fba62c86","pid":424,"level":50,"err":{"message":"docstore api responded with non-success code: 404","name":"Error","stack":"Error: docstore api responded with non-success code: 404\n    at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:137:19)\n    at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:188:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1171:10)\n    at Request.emit (events.js:95:17)\n    at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:180:16)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickDomainCallback (node.js:502:13)\n"},"doc_id":"56e1f35a4ebb1d2f007bd8aa","project_id":"561555a294fd8e2e00cce7a3","msg":"error finding element for getDocument","time":"2017-04-28T03:13:58.209Z","v":0}
{"name":"web-sharelatex","hostname":"8db5fba62c86","pid":424,"level":50,"err":{"message":"docstore api responded with non-success code: 404","name":"Error","stack":"Error: docstore api responded with non-success code: 404\n    at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:137:19)\n    at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:188:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1171:10)\n    at Request.emit (events.js:95:17)\n    at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:180:16)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickDomainCallback (node.js:502:13)\n"},"url":"/project/561555a294fd8e2e00cce7a3/doc/56e1f35a4ebb1d2f007bd8aa","method":"GET","user":null,"msg":"error passed to top level next middlewear","time":"2017-04-28T03:13:58.210Z","v":0}
{"name":"web-sharelatex","hostname":"8db5fba62c86","pid":424,"level":50,"err":{"message":"docstore api responded with non-success code: 404","name":"Error","stack":"Error: docstore api responded with non-success code: 404\n    at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:137:19)\n    at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:188:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1171:10)\n    at Request.emit (events.js:95:17)\n    at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:180:16)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickDomainCallback (node.js:502:13)\n"},"project_id":"561555a294fd8e2e00cce7a3","doc_id":"56e1f35a4ebb1d2f007bd8a8","msg":"error getting doc from docstore","time":"2017-04-28T03:14:31.792Z","v":0}
```

**Comment by roddhjav** [comment]
Hi,

I have exactly the same issue. Does anyone has a solution for this problem?

**Comment by giovannesant** [comment]
Hi, I just deleted all docker things, flushed iptables rules and recreated the container. After that, I have reaplied the same iptables rules. Now it works. But I'dont know what the really issue, sorry about that.
