### ISSUE TITLE
Docker compose mongo-db migration errors

### ISSUE THREAD

**Issue by elagil** [sharelatex/sharelatex#582]
Hello,

I have installed sharelatex on a server using the docker-compose approach. It seems to work smoothly but I find this in the log-files of sharelatex:

```

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]

Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://mongo/sharelatex
/var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:797
          throw err;
          ^

TypeError: db.collection is not a function
    at /var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:20:24
    at args.push (/var/www/sharelatex/node_modules/mongodb/lib/utils.js:404:72)
    at /var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:255:5
    at connectCallback (/var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:933:5)
    at /var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:794:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Warning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://mongo/sharelatex

/var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:797
          throw err;
          ^

TypeError: db.collection is not a function
    at /var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:20:24
    at args.push (/var/www/sharelatex/node_modules/mongodb/lib/utils.js:404:72)
    at /var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:255:5
    at connectCallback (/var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:933:5)
    at /var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:794:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Use --force to continue.

Aborted due to warnings.
```

Any idea what could be causing this? I am suspecting a wrong mongo version for some of the calls (v3.6.3 is used for mongo-db, v4.0.8 of redis), or is it because no files actually need to be migrated?

Thanks for any comments!

**Comment by msimonin** [comment]
I'm actually hitting this bug preventing me to migrate to version 0.6.3.

**Comment by jdleesmiller** [comment]
Thanks for reporting this. We thought we'd fixed this, but maybe not; we are looking into it.

**Comment by henryoswald** [comment]
Hi, can you try v1.2.1 please and see if that fixes the problem?

**Comment by beenje** [comment]
It looks like the migration went fine with v1.2.1.

I didn't use it yesterday because "latest" was still "v1.2.0" but I see that the tag was changed now.
Thanks!

```
*** Running /etc/my_init.d/99_migrate.sh...
/usr/bin/node
/usr/bin/grunt
total 56
drwxr-xr-x  2 www-data www-data  4096 Mar  8 10:43 .
drwxr-xr-x 20 www-data www-data  4096 Mar  8 10:44 ..
-rw-r--r--  1 www-data www-data  5031 Mar  8 10:43 1_move_doc_lines_to_doc_collection.coffee
-rw-r--r--  1 www-data www-data  5936 Mar  8 10:43 2_doc_lines_delete_from_project.coffee
-rw-r--r--  1 www-data www-data 10627 Mar  8 10:43 3_pack_docHistory_collection.coffee
-rw-r--r--  1 www-data www-data   788 Mar  8 10:43 4_update_user_features.coffee
-rw-r--r--  1 www-data www-data  3526 Mar  8 10:43 5_remove_holding_accounts.coffee
-rw-r--r--  1 www-data www-data   652 Mar  8 10:43 6_add_track_changes_feature.coffee
-rw-r--r--  1 www-data www-data   733 Mar  8 10:43 7_add_track_changes_feature_again.coffee
-rw-r--r--  1 www-data www-data   335 Mar  8 10:43 about_migrations.md
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bunyan" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Loading "bunyan.js" tasks...OK
+ bunyan

Registering "grunt-execute" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Loading "execute.js" tasks...OK
+ execute

Registering "grunt-available-tasks" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Loading "available_tasks.js" tasks...OK
+ availabletasks

Registering "grunt-concurrent" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-shell" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell

Registering "./tasks" tasks.
Loading "CreateAndDestoryUsers.coffee" tasks...OK
+ user:create-admin, user:delete
Loading "ProjectSize.coffee" tasks...OK
>> No tasks were registered or unregistered.
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ check, check:make, check:mongo, check:redis, default, help, install, install:all, install:chat, install:clsi, install:contacts, install:docstore, install:document-updater, install:filestore, install:notifications, install:real-time, install:spelling, install:tags, install:track-changes, install:web, migrate, postinstall, run, run:all, update, update:all

Running tasks: migrate

Running "migrate" task

Running "coffee:migrate" (coffee) task
Verifying property coffee.migrate exists in config...OK
Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
Files: migrations/4_update_user_features.coffee -> migrations/4_update_user_features.js
Files: migrations/5_remove_holding_accounts.coffee -> migrations/5_remove_holding_accounts.js
Files: migrations/6_add_track_changes_feature.coffee -> migrations/6_add_track_changes_feature.js
Files: migrations/7_add_track_changes_feature_again.coffee -> migrations/7_add_track_changes_feature_again.js
Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
Reading migrations/2_doc_lines_delete_from_project.coffee...OK
Writing migrations/2_doc_lines_delete_from_project.js...OK
Reading migrations/3_pack_docHistory_collection.coffee...OK
Writing migrations/3_pack_docHistory_collection.js...OK
Reading migrations/4_update_user_features.coffee...OK
Writing migrations/4_update_user_features.js...OK
Reading migrations/5_remove_holding_accounts.coffee...OK
Writing migrations/5_remove_holding_accounts.js...OK
Reading migrations/6_add_track_changes_feature.coffee...OK
Writing migrations/6_add_track_changes_feature.js...OK
Reading migrations/7_add_track_changes_feature_again.coffee...OK
Writing migrations/7_add_track_changes_feature_again.js...OK

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://sharelatex_mongo/sharelatex
target migrations:
	6_add_track_changes_feature
	7_add_track_changes_feature_again
migrate `6_add_track_changes_feature`
>> enabling trackChanges feature:  { '$set': { 'features.trackChanges': true } }
finished enabling trackChanges feature
migration done
migrate `7_add_track_changes_feature_again`
>> enabling trackChanges feature:  { '$set': { 'features.trackChanges': true } }
finished enabling trackChanges feature
migration done

Done, without errors.
All migrations finished
```

**Comment by henryoswald** [comment]
great to hear!
